// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// ApprovalResult describes the decision and associated metadata of a manual
/// approval of a build.
public struct ApprovalResult: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Email of the user that called the ApproveBuild API to
  /// approve or reject a build at the time that the API was called.
  public var approverAccount: Swift.String = Swift.String()

  /// Output only. The time when the approval decision was made.
  public var approvalTime: GoogleWKT.WKTTimestamp? = nil

  /// Required. The decision of this manual approval.
  public var decision: ApprovalResult.Decision = ApprovalResult.Decision()

  /// Optional. An optional comment for this manual approval result.
  public var comment: Swift.String = Swift.String()

  /// Optional. An optional URL tied to this manual approval result. This field
  /// is essentially the same as comment, except that it will be rendered by the
  /// UI differently. An example use case is a link to an external job that
  /// approved this Build.
  public var url: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ApprovalResult`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ApprovalResult().with { $0.approverAccount = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let approverAccount = CodingKeys(stringValue: "approverAccount")
    static let approvalTime = CodingKeys(stringValue: "approvalTime")
    static let decision = CodingKeys(stringValue: "decision")
    static let comment = CodingKeys(stringValue: "comment")
    static let url = CodingKeys(stringValue: "url")

    static let _knownKeys: Set<Swift.String> = [
      "approverAccount",
      "approvalTime",
      "decision",
      "comment",
      "url",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .approverAccount) {
      self.approverAccount = value
    }
    self.approvalTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .approvalTime)
    if let value = try container.decodeIfPresent(ApprovalResult.Decision.self, forKey: .decision) {
      self.decision = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .comment) {
      self.comment = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .url) {
      self.url = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.approverAccount, forKey: .approverAccount)
    try container.encodeIfPresent(self.approvalTime, forKey: .approvalTime)
    try container.encode(self.decision, forKey: .decision)
    try container.encode(self.comment, forKey: .comment)
    try container.encode(self.url, forKey: .url)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Specifies whether or not this manual approval result is to approve
  /// or reject a build.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Decision: Codable, Equatable, Sendable {
    /// Default enum type. This should not be used.
    case unspecified
    /// Build is approved.
    case approved
    /// Build is rejected.
    case rejected
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .approved: return 1
      case .rejected: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "DECISION_UNSPECIFIED"
      case .approved: return "APPROVED"
      case .rejected: return "REJECTED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Decision/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "DECISION_UNSPECIFIED": self = .unspecified
      case "APPROVED": self = .approved
      case "REJECTED": self = .rejected
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Decision/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .approved
      case 2: self = .rejected
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("DECISION_UNSPECIFIED")
      case .approved: return try container.encode("APPROVED")
      case .rejected: return try container.encode("REJECTED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.cloudbuild.v1.ApprovalResult"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
