// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Artifacts produced by a build that should be uploaded upon
/// successful completion of all build steps.
public struct Artifacts: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// A list of images to be pushed upon the successful completion of all build
  /// steps.
  ///
  /// The images will be pushed using the builder service account's credentials.
  ///
  /// The digests of the pushed images will be stored in the Build resource's
  /// results field.
  ///
  /// If any of the images fail to be pushed, the build is marked FAILURE.
  public var images: [Swift.String] = []

  /// A list of objects to be uploaded to Cloud Storage upon successful
  /// completion of all build steps.
  ///
  /// Files in the workspace matching specified paths globs will be uploaded to
  /// the specified Cloud Storage location using the builder service account's
  /// credentials.
  ///
  /// The location and generation of the uploaded objects will be stored in the
  /// Build resource's results field.
  ///
  /// If any objects fail to be pushed, the build is marked FAILURE.
  public var objects: Artifacts.ArtifactObjects? = nil

  /// A list of Maven artifacts to be uploaded to Artifact Registry upon
  /// successful completion of all build steps.
  ///
  /// Artifacts in the workspace matching specified paths globs will be uploaded
  /// to the specified Artifact Registry repository using the builder service
  /// account's credentials.
  ///
  /// If any artifacts fail to be pushed, the build is marked FAILURE.
  public var mavenArtifacts: [Artifacts.MavenArtifact] = []

  /// Optional. A list of Go modules to be uploaded to Artifact Registry upon
  /// successful completion of all build steps.
  ///
  /// If any objects fail to be pushed, the build is marked FAILURE.
  public var goModules: [Artifacts.GoModule] = []

  /// A list of Python packages to be uploaded to Artifact Registry upon
  /// successful completion of all build steps.
  ///
  /// The build service account credentials will be used to perform the upload.
  ///
  /// If any objects fail to be pushed, the build is marked FAILURE.
  public var pythonPackages: [Artifacts.PythonPackage] = []

  /// A list of npm packages to be uploaded to Artifact Registry upon
  /// successful completion of all build steps.
  ///
  /// Npm packages in the specified paths will be uploaded
  /// to the specified Artifact Registry repository using the builder service
  /// account's credentials.
  ///
  /// If any packages fail to be pushed, the build is marked FAILURE.
  public var npmPackages: [Artifacts.NpmPackage] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Artifacts`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Artifacts().with { $0.images = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let images = CodingKeys(stringValue: "images")
    static let objects = CodingKeys(stringValue: "objects")
    static let mavenArtifacts = CodingKeys(stringValue: "mavenArtifacts")
    static let goModules = CodingKeys(stringValue: "goModules")
    static let pythonPackages = CodingKeys(stringValue: "pythonPackages")
    static let npmPackages = CodingKeys(stringValue: "npmPackages")

    static let _knownKeys: Set<Swift.String> = [
      "images",
      "objects",
      "mavenArtifacts",
      "goModules",
      "pythonPackages",
      "npmPackages",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .images) {
      self.images = value
    }
    self.objects = try container.decodeIfPresent(Artifacts.ArtifactObjects.self, forKey: .objects)
    if let value = try container.decodeIfPresent(
      [Artifacts.MavenArtifact].self, forKey: .mavenArtifacts)
    {
      self.mavenArtifacts = value
    }
    if let value = try container.decodeIfPresent([Artifacts.GoModule].self, forKey: .goModules) {
      self.goModules = value
    }
    if let value = try container.decodeIfPresent(
      [Artifacts.PythonPackage].self, forKey: .pythonPackages)
    {
      self.pythonPackages = value
    }
    if let value = try container.decodeIfPresent([Artifacts.NpmPackage].self, forKey: .npmPackages)
    {
      self.npmPackages = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.images, forKey: .images)
    try container.encodeIfPresent(self.objects, forKey: .objects)
    try container.encode(self.mavenArtifacts, forKey: .mavenArtifacts)
    try container.encode(self.goModules, forKey: .goModules)
    try container.encode(self.pythonPackages, forKey: .pythonPackages)
    try container.encode(self.npmPackages, forKey: .npmPackages)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Files in the workspace to upload to Cloud Storage upon successful
  /// completion of all build steps.
  public struct ArtifactObjects: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Cloud Storage bucket and optional object path, in the form
    /// "gs://bucket/path/to/somewhere/". (see [Bucket Name
    /// Requirements](https://cloud.google.com/storage/docs/bucket-naming#requirements)).
    ///
    /// Files in the workspace matching any path pattern will be uploaded to
    /// Cloud Storage with this location as a prefix.
    public var location: Swift.String = Swift.String()

    /// Path globs used to match files in the build's workspace.
    public var paths: [Swift.String] = []

    /// Output only. Stores timing information for pushing all artifact objects.
    public var timing: TimeSpan? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ArtifactObjects`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ArtifactObjects().with { $0.location = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let location = CodingKeys(stringValue: "location")
      static let paths = CodingKeys(stringValue: "paths")
      static let timing = CodingKeys(stringValue: "timing")

      static let _knownKeys: Set<Swift.String> = [
        "location",
        "paths",
        "timing",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .location) {
        self.location = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .paths) {
        self.paths = value
      }
      self.timing = try container.decodeIfPresent(TimeSpan.self, forKey: .timing)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.location, forKey: .location)
      try container.encode(self.paths, forKey: .paths)
      try container.encodeIfPresent(self.timing, forKey: .timing)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.devtools.cloudbuild.v1.Artifacts.ArtifactObjects"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// A Maven artifact to upload to Artifact Registry upon successful completion
  /// of all build steps.
  public struct MavenArtifact: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Artifact Registry repository, in the form
    /// "https://$REGION-maven.pkg.dev/$PROJECT/$REPOSITORY"
    ///
    /// Artifact in the workspace specified by path will be uploaded to
    /// Artifact Registry with this location as a prefix.
    public var repository: Swift.String = Swift.String()

    /// Optional. Path to an artifact in the build's workspace to be uploaded to
    /// Artifact Registry.
    /// This can be either an absolute path,
    /// e.g. /workspace/my-app/target/my-app-1.0.SNAPSHOT.jar
    /// or a relative path from /workspace,
    /// e.g. my-app/target/my-app-1.0.SNAPSHOT.jar.
    public var path: Swift.String = Swift.String()

    /// Maven `artifactId` value used when uploading the artifact to Artifact
    /// Registry.
    public var artifactId: Swift.String = Swift.String()

    /// Maven `groupId` value used when uploading the artifact to Artifact
    /// Registry.
    public var groupId: Swift.String = Swift.String()

    /// Maven `version` value used when uploading the artifact to Artifact
    /// Registry.
    public var version: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `MavenArtifact`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = MavenArtifact().with { $0.repository = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let repository = CodingKeys(stringValue: "repository")
      static let path = CodingKeys(stringValue: "path")
      static let artifactId = CodingKeys(stringValue: "artifactId")
      static let groupId = CodingKeys(stringValue: "groupId")
      static let version = CodingKeys(stringValue: "version")

      static let _knownKeys: Set<Swift.String> = [
        "repository",
        "path",
        "artifactId",
        "groupId",
        "version",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .repository) {
        self.repository = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .path) {
        self.path = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .artifactId) {
        self.artifactId = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .groupId) {
        self.groupId = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .version) {
        self.version = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.repository, forKey: .repository)
      try container.encode(self.path, forKey: .path)
      try container.encode(self.artifactId, forKey: .artifactId)
      try container.encode(self.groupId, forKey: .groupId)
      try container.encode(self.version, forKey: .version)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.devtools.cloudbuild.v1.Artifacts.MavenArtifact"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Go module to upload to Artifact Registry upon successful completion of all
  /// build steps. A module refers to all dependencies in a go.mod file.
  public struct GoModule: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. Artifact Registry repository name.
    ///
    /// Specified Go modules will be zipped and uploaded to Artifact Registry
    /// with this location as a prefix.
    /// e.g. my-go-repo
    public var repositoryName: Swift.String = Swift.String()

    /// Optional. Location of the Artifact Registry repository. i.e. us-east1
    /// Defaults to the build’s location.
    public var repositoryLocation: Swift.String = Swift.String()

    /// Optional. Project ID of the Artifact Registry repository.
    /// Defaults to the build project.
    public var repositoryProjectId: Swift.String = Swift.String()

    /// Optional. Source path of the go.mod file in the build's workspace. If not
    /// specified, this will default to the current directory.
    /// e.g. ~/code/go/mypackage
    public var sourcePath: Swift.String = Swift.String()

    /// Optional. The Go module's "module path".
    /// e.g. example.com/foo/v2
    public var modulePath: Swift.String = Swift.String()

    /// Optional. The Go module's semantic version in the form vX.Y.Z. e.g.
    /// v0.1.1 Pre-release identifiers can also be added by appending a dash and
    /// dot separated ASCII alphanumeric characters and hyphens.
    /// e.g. v0.2.3-alpha.x.12m.5
    public var moduleVersion: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `GoModule`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GoModule().with { $0.repositoryName = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let repositoryName = CodingKeys(stringValue: "repositoryName")
      static let repositoryLocation = CodingKeys(stringValue: "repositoryLocation")
      static let repositoryProjectId = CodingKeys(stringValue: "repositoryProjectId")
      static let sourcePath = CodingKeys(stringValue: "sourcePath")
      static let modulePath = CodingKeys(stringValue: "modulePath")
      static let moduleVersion = CodingKeys(stringValue: "moduleVersion")

      static let _knownKeys: Set<Swift.String> = [
        "repositoryName",
        "repositoryLocation",
        "repositoryProjectId",
        "sourcePath",
        "modulePath",
        "moduleVersion",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .repositoryName) {
        self.repositoryName = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .repositoryLocation) {
        self.repositoryLocation = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .repositoryProjectId)
      {
        self.repositoryProjectId = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sourcePath) {
        self.sourcePath = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .modulePath) {
        self.modulePath = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .moduleVersion) {
        self.moduleVersion = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.repositoryName, forKey: .repositoryName)
      try container.encode(self.repositoryLocation, forKey: .repositoryLocation)
      try container.encode(self.repositoryProjectId, forKey: .repositoryProjectId)
      try container.encode(self.sourcePath, forKey: .sourcePath)
      try container.encode(self.modulePath, forKey: .modulePath)
      try container.encode(self.moduleVersion, forKey: .moduleVersion)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.devtools.cloudbuild.v1.Artifacts.GoModule"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Python package to upload to Artifact Registry upon successful completion
  /// of all build steps. A package can encapsulate multiple objects to be
  /// uploaded to a single repository.
  public struct PythonPackage: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Artifact Registry repository, in the form
    /// "https://$REGION-python.pkg.dev/$PROJECT/$REPOSITORY"
    ///
    /// Files in the workspace matching any path pattern will be uploaded to
    /// Artifact Registry with this location as a prefix.
    public var repository: Swift.String = Swift.String()

    /// Path globs used to match files in the build's workspace. For Python/
    /// Twine, this is usually `dist/*`, and sometimes additionally an `.asc`
    /// file.
    public var paths: [Swift.String] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `PythonPackage`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PythonPackage().with { $0.repository = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let repository = CodingKeys(stringValue: "repository")
      static let paths = CodingKeys(stringValue: "paths")

      static let _knownKeys: Set<Swift.String> = [
        "repository",
        "paths",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .repository) {
        self.repository = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .paths) {
        self.paths = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.repository, forKey: .repository)
      try container.encode(self.paths, forKey: .paths)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.devtools.cloudbuild.v1.Artifacts.PythonPackage"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Npm package to upload to Artifact Registry upon successful completion
  /// of all build steps.
  public struct NpmPackage: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Artifact Registry repository, in the form
    /// "https://$REGION-npm.pkg.dev/$PROJECT/$REPOSITORY"
    ///
    /// Npm package in the workspace specified by path will be zipped and
    /// uploaded to Artifact Registry with this location as a prefix.
    public var repository: Swift.String = Swift.String()

    /// Optional. Path to the package.json.
    /// e.g. workspace/path/to/package
    ///
    /// Only one of `archive` or `package_path` can be specified.
    public var packagePath: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `NpmPackage`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = NpmPackage().with { $0.repository = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let repository = CodingKeys(stringValue: "repository")
      static let packagePath = CodingKeys(stringValue: "packagePath")

      static let _knownKeys: Set<Swift.String> = [
        "repository",
        "packagePath",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .repository) {
        self.repository = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .packagePath) {
        self.packagePath = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.repository, forKey: .repository)
      try container.encode(self.packagePath, forKey: .packagePath)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.devtools.cloudbuild.v1.Artifacts.NpmPackage"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.cloudbuild.v1.Artifacts"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
