// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Configuration for an automated build in response to source repository
/// changes.
public struct BuildTrigger: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The `Trigger` name with format:
  /// `projects/{project}/locations/{location}/triggers/{trigger}`, where
  /// {trigger} is a unique identifier generated by the service.
  public var resourceName: Swift.String = Swift.String()

  /// Output only. Unique identifier of the trigger.
  public var id: Swift.String = Swift.String()

  /// Human-readable description of this trigger.
  public var description: Swift.String = Swift.String()

  /// User-assigned name of the trigger. Must be unique within the project.
  /// Trigger names must meet the following requirements:
  ///
  /// + They must contain only alphanumeric characters and dashes.
  /// + They can be 1-64 characters long.
  /// + They must begin and end with an alphanumeric character.
  public var name: Swift.String = Swift.String()

  /// Tags for annotation of a `BuildTrigger`
  public var tags: [Swift.String] = []

  /// Template describing the types of source changes to trigger a build.
  ///
  /// Branch and tag names in trigger templates are interpreted as regular
  /// expressions. Any branch or tag change that matches that regular expression
  /// will trigger a build.
  ///
  /// Mutually exclusive with `github`.
  public var triggerTemplate: RepoSource? = nil

  /// GitHubEventsConfig describes the configuration of a trigger that creates
  /// a build whenever a GitHub event is received.
  ///
  /// Mutually exclusive with `trigger_template`.
  public var github: GitHubEventsConfig? = nil

  /// PubsubConfig describes the configuration of a trigger that
  /// creates a build whenever a Pub/Sub message is published.
  public var pubsubConfig: PubsubConfig? = nil

  /// WebhookConfig describes the configuration of a trigger that
  /// creates a build whenever a webhook is sent to a trigger's webhook URL.
  public var webhookConfig: WebhookConfig? = nil

  /// Output only. Time when the trigger was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// If true, the trigger will never automatically execute a build.
  public var disabled: Swift.Bool = Swift.Bool()

  /// Substitutions for Build resource. The keys must match the following
  /// regular expression: `^_[A-Z0-9_]+$`.
  public var substitutions: [Swift.String: Swift.String] = [:]

  /// ignored_files and included_files are file glob matches using
  /// https://golang.org/pkg/path/filepath/#Match extended with support for "**".
  ///
  /// If ignored_files and changed files are both empty, then they are
  /// not used to determine whether or not to trigger a build.
  ///
  /// If ignored_files is not empty, then we ignore any files that match
  /// any of the ignored_file globs. If the change has no files that are
  /// outside of the ignored_files globs, then we do not trigger a build.
  public var ignoredFiles: [Swift.String] = []

  /// If any of the files altered in the commit pass the ignored_files
  /// filter and included_files is empty, then as far as this filter is
  /// concerned, we should trigger the build.
  ///
  /// If any of the files altered in the commit pass the ignored_files
  /// filter and included_files is not empty, then we make sure that at
  /// least one of those files matches a included_files glob. If not,
  /// then we do not trigger a build.
  public var includedFiles: [Swift.String] = []

  /// Optional. A Common Expression Language string.
  public var filter: Swift.String = Swift.String()

  /// The repo and ref of the repository from which to build. This field
  /// is used only for those triggers that do not respond to SCM events.
  /// Triggers that respond to such events build source at whatever commit
  /// caused the event.
  /// This field is currently only used by Webhook, Pub/Sub, Manual, and Cron
  /// triggers.
  public var sourceToBuild: GitRepoSource? = nil

  /// The service account used for all user-controlled operations including
  /// UpdateBuildTrigger, RunBuildTrigger, CreateBuild, and CancelBuild.
  /// If no service account is set and the legacy Cloud Build service account
  /// (`[PROJECT_NUM]@cloudbuild.gserviceaccount.com`) is the default for the
  /// project then it will be used instead.
  /// Format: `projects/{PROJECT_ID}/serviceAccounts/{ACCOUNT_ID_OR_EMAIL}`
  public var serviceAccount: Swift.String = Swift.String()

  /// The configuration of a trigger that creates a build whenever an event from
  /// Repo API is received.
  public var repositoryEventConfig: RepositoryEventConfig? = nil

  /// Template describing the Build request to make when the trigger is matched.
  /// At least one of the template fields must be provided.
  public var buildTemplate: OneOf_BuildTemplate? = nil

  /// Initialize a new instance of `BuildTrigger`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BuildTrigger().with { $0.resourceName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case resourceName = "resourceName"
    case id = "id"
    case description = "description"
    case name = "name"
    case tags = "tags"
    case triggerTemplate = "triggerTemplate"
    case github = "github"
    case pubsubConfig = "pubsubConfig"
    case webhookConfig = "webhookConfig"
    case autodetect = "autodetect"
    case build = "build"
    case filename = "filename"
    case gitFileSource = "gitFileSource"
    case createTime = "createTime"
    case disabled = "disabled"
    case substitutions = "substitutions"
    case ignoredFiles = "ignoredFiles"
    case includedFiles = "includedFiles"
    case filter = "filter"
    case sourceToBuild = "sourceToBuild"
    case serviceAccount = "serviceAccount"
    case repositoryEventConfig = "repositoryEventConfig"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.resourceName = try container.decode(Swift.String.self, forKey: .resourceName)
    self.id = try container.decode(Swift.String.self, forKey: .id)
    self.description = try container.decode(Swift.String.self, forKey: .description)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.tags = try container.decode([Swift.String].self, forKey: .tags)
    self.triggerTemplate = try container.decodeIfPresent(RepoSource.self, forKey: .triggerTemplate)
    self.github = try container.decodeIfPresent(GitHubEventsConfig.self, forKey: .github)
    self.pubsubConfig = try container.decodeIfPresent(PubsubConfig.self, forKey: .pubsubConfig)
    self.webhookConfig = try container.decodeIfPresent(WebhookConfig.self, forKey: .webhookConfig)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .createTime)
    self.disabled = try container.decode(Swift.Bool.self, forKey: .disabled)
    self.substitutions = try container.decode(
      [Swift.String: Swift.String].self, forKey: .substitutions)
    self.ignoredFiles = try container.decode([Swift.String].self, forKey: .ignoredFiles)
    self.includedFiles = try container.decode([Swift.String].self, forKey: .includedFiles)
    self.filter = try container.decode(Swift.String.self, forKey: .filter)
    self.sourceToBuild = try container.decodeIfPresent(GitRepoSource.self, forKey: .sourceToBuild)
    self.serviceAccount = try container.decode(Swift.String.self, forKey: .serviceAccount)
    self.repositoryEventConfig = try container.decodeIfPresent(
      RepositoryEventConfig.self, forKey: .repositoryEventConfig)

    var buildTemplate: OneOf_BuildTemplate? = nil
    let buildTemplateCheckAndSet = {
      if buildTemplate != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'buildTemplate'"))
      }
      buildTemplate = $0
    }
    if let autodetect = try container.decodeIfPresent(Swift.Bool.self, forKey: .autodetect) {
      try buildTemplateCheckAndSet(.autodetect(autodetect))
    }
    if let build = try container.decodeIfPresent(Build?.self, forKey: .build) {
      try buildTemplateCheckAndSet(.build(build))
    }
    if let filename = try container.decodeIfPresent(Swift.String.self, forKey: .filename) {
      try buildTemplateCheckAndSet(.filename(filename))
    }
    if let gitFileSource = try container.decodeIfPresent(
      GitFileSource?.self, forKey: .gitFileSource)
    {
      try buildTemplateCheckAndSet(.gitFileSource(gitFileSource))
    }
    self.buildTemplate = buildTemplate
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.resourceName, forKey: .resourceName)
    try container.encode(self.id, forKey: .id)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.tags, forKey: .tags)
    try container.encode(self.triggerTemplate, forKey: .triggerTemplate)
    try container.encode(self.github, forKey: .github)
    try container.encode(self.pubsubConfig, forKey: .pubsubConfig)
    try container.encode(self.webhookConfig, forKey: .webhookConfig)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.disabled, forKey: .disabled)
    try container.encode(self.substitutions, forKey: .substitutions)
    try container.encode(self.ignoredFiles, forKey: .ignoredFiles)
    try container.encode(self.includedFiles, forKey: .includedFiles)
    try container.encode(self.filter, forKey: .filter)
    try container.encode(self.sourceToBuild, forKey: .sourceToBuild)
    try container.encode(self.serviceAccount, forKey: .serviceAccount)
    try container.encode(self.repositoryEventConfig, forKey: .repositoryEventConfig)

    if let choice = self.buildTemplate {
      switch choice {
      case .autodetect(let value):
        try container.encode(value, forKey: .autodetect)
      case .build(let value):
        try container.encode(value, forKey: .build)
      case .filename(let value):
        try container.encode(value, forKey: .filename)
      case .gitFileSource(let value):
        try container.encode(value, forKey: .gitFileSource)
      }
    }
  }

  /// Template describing the Build request to make when the trigger is matched.
  /// At least one of the template fields must be provided.
  public enum OneOf_BuildTemplate: Codable, Equatable, Sendable {
    /// Autodetect build configuration.  The following precedence is used (case
    /// insensitive):
    ///
    /// 1. cloudbuild.yaml
    /// 2. cloudbuild.yml
    /// 3. cloudbuild.json
    /// 4. Dockerfile
    ///
    /// Currently only available for GitHub App Triggers.
    case autodetect(Swift.Bool)
    /// Contents of the build template.
    indirect case build(Build?)
    /// Path, from the source root, to the build configuration file
    /// (i.e. cloudbuild.yaml).
    case filename(Swift.String)
    /// The file source describing the local or remote Build template.
    indirect case gitFileSource(GitFileSource?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.cloudbuild.v1.BuildTrigger"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
