// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A build resource in the Cloud Build API.
///
/// At a high level, a `Build` describes where to find source code, how to build
/// it (for example, the builder image to run on the source), and where to store
/// the built artifacts.
///
/// Fields can include the following variables, which will be expanded when the
/// build is created:
///
/// - $PROJECT_ID: the project ID of the build.
/// - $PROJECT_NUMBER: the project number of the build.
/// - $LOCATION: the location/region of the build.
/// - $BUILD_ID: the autogenerated ID of the build.
/// - $REPO_NAME: the source repository name specified by RepoSource.
/// - $BRANCH_NAME: the branch name specified by RepoSource.
/// - $TAG_NAME: the tag name specified by RepoSource.
/// - $REVISION_ID or $COMMIT_SHA: the commit SHA specified by RepoSource or
///   resolved from the specified branch or tag.
/// - $SHORT_SHA: first 7 characters of $REVISION_ID or $COMMIT_SHA.
public struct Build: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The 'Build' name with format:
  /// `projects/{project}/locations/{location}/builds/{build}`, where {build}
  /// is a unique identifier generated by the service.
  public var name: Swift.String = Swift.String()

  /// Output only. Unique identifier of the build.
  public var id: Swift.String = Swift.String()

  /// Output only. ID of the project.
  public var projectId: Swift.String = Swift.String()

  /// Output only. Status of the build.
  public var status: Build.Status = Build.Status()

  /// Output only. Customer-readable message about the current status.
  public var statusDetail: Swift.String = Swift.String()

  /// Optional. The location of the source files to build.
  public var source: Source? = nil

  /// Required. The operations to be performed on the workspace.
  public var steps: [BuildStep] = []

  /// Output only. Results of the build.
  public var results: Results? = nil

  /// Output only. Time at which the request to create the build was received.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Time at which execution of the build was started.
  public var startTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Time at which execution of the build was finished.
  ///
  /// The difference between finish_time and start_time is the duration of the
  /// build's execution.
  public var finishTime: GoogleWKT.WKTTimestamp? = nil

  /// Amount of time that this build should be allowed to run, to second
  /// granularity. If this amount of time elapses, work on the build will cease
  /// and the build status will be `TIMEOUT`.
  ///
  /// `timeout` starts ticking from `startTime`.
  ///
  /// Default time is 60 minutes.
  public var timeout: GoogleWKT.WKTDuration? = nil

  /// A list of images to be pushed upon the successful completion of all build
  /// steps.
  ///
  /// The images are pushed using the builder service account's credentials.
  ///
  /// The digests of the pushed images will be stored in the `Build` resource's
  /// results field.
  ///
  /// If any of the images fail to be pushed, the build status is marked
  /// `FAILURE`.
  public var images: [Swift.String] = []

  /// TTL in queue for this build. If provided and the build is enqueued longer
  /// than this value, the build will expire and the build status will be
  /// `EXPIRED`.
  ///
  /// The TTL starts ticking from create_time.
  public var queueTtl: GoogleWKT.WKTDuration? = nil

  /// Artifacts produced by the build that should be uploaded upon
  /// successful completion of all build steps.
  public var artifacts: Artifacts? = nil

  /// Cloud Storage bucket where logs should be written (see
  /// [Bucket Name
  /// Requirements](https://cloud.google.com/storage/docs/bucket-naming#requirements)).
  /// Logs file names will be of the format `${logs_bucket}/log-${build_id}.txt`.
  public var logsBucket: Swift.String = Swift.String()

  /// Output only. A permanent fixed identifier for source.
  public var sourceProvenance: SourceProvenance? = nil

  /// Output only. The ID of the `BuildTrigger` that triggered this build, if it
  /// was triggered automatically.
  public var buildTriggerId: Swift.String = Swift.String()

  /// Special options for this build.
  public var options: BuildOptions? = nil

  /// Output only. URL to logs for this build in Google Cloud Console.
  public var logUrl: Swift.String = Swift.String()

  /// Substitutions data for `Build` resource.
  public var substitutions: [Swift.String: Swift.String] = [:]

  /// Tags for annotation of a `Build`. These are not docker tags.
  public var tags: [Swift.String] = []

  /// Secrets to decrypt using Cloud Key Management Service.
  /// Note: Secret Manager is the recommended technique
  /// for managing sensitive data with Cloud Build. Use `available_secrets` to
  /// configure builds to access secrets from Secret Manager. For instructions,
  /// see: https://cloud.google.com/cloud-build/docs/securing-builds/use-secrets
  public var secrets: [Secret] = []

  /// Output only. Stores timing information for phases of the build. Valid keys
  /// are:
  ///
  /// * BUILD: time to execute all build steps.
  /// * PUSH: time to push all artifacts including docker images and non docker
  /// artifacts.
  /// * FETCHSOURCE: time to fetch source.
  /// * SETUPBUILD: time to set up build.
  ///
  /// If the build does not specify source or images,
  /// these keys will not be included.
  public var timing: [Swift.String: TimeSpan] = [:]

  /// Output only. Describes this build's approval configuration, status,
  /// and result.
  public var approval: BuildApproval? = nil

  /// IAM service account whose credentials will be used at build runtime.
  /// Must be of the format `projects/{PROJECT_ID}/serviceAccounts/{ACCOUNT}`.
  /// ACCOUNT can be email address or uniqueId of the service account.
  ///
  public var serviceAccount: Swift.String = Swift.String()

  /// Secrets and secret environment variables.
  public var availableSecrets: Secrets? = nil

  /// Output only. Non-fatal problems encountered during the execution of the
  /// build.
  public var warnings: [Build.Warning] = []

  /// Optional. Configuration for git operations.
  public var gitConfig: GitConfig? = nil

  /// Output only. Contains information about the build when status=FAILURE.
  public var failureInfo: Build.FailureInfo? = nil

  /// Optional. Dependencies that the Cloud Build worker will fetch before
  /// executing user steps.
  public var dependencies: [Dependency] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Build`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Build().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let id = CodingKeys(stringValue: "id")
    static let projectId = CodingKeys(stringValue: "projectId")
    static let status = CodingKeys(stringValue: "status")
    static let statusDetail = CodingKeys(stringValue: "statusDetail")
    static let source = CodingKeys(stringValue: "source")
    static let steps = CodingKeys(stringValue: "steps")
    static let results = CodingKeys(stringValue: "results")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let startTime = CodingKeys(stringValue: "startTime")
    static let finishTime = CodingKeys(stringValue: "finishTime")
    static let timeout = CodingKeys(stringValue: "timeout")
    static let images = CodingKeys(stringValue: "images")
    static let queueTtl = CodingKeys(stringValue: "queueTtl")
    static let artifacts = CodingKeys(stringValue: "artifacts")
    static let logsBucket = CodingKeys(stringValue: "logsBucket")
    static let sourceProvenance = CodingKeys(stringValue: "sourceProvenance")
    static let buildTriggerId = CodingKeys(stringValue: "buildTriggerId")
    static let options = CodingKeys(stringValue: "options")
    static let logUrl = CodingKeys(stringValue: "logUrl")
    static let substitutions = CodingKeys(stringValue: "substitutions")
    static let tags = CodingKeys(stringValue: "tags")
    static let secrets = CodingKeys(stringValue: "secrets")
    static let timing = CodingKeys(stringValue: "timing")
    static let approval = CodingKeys(stringValue: "approval")
    static let serviceAccount = CodingKeys(stringValue: "serviceAccount")
    static let availableSecrets = CodingKeys(stringValue: "availableSecrets")
    static let warnings = CodingKeys(stringValue: "warnings")
    static let gitConfig = CodingKeys(stringValue: "gitConfig")
    static let failureInfo = CodingKeys(stringValue: "failureInfo")
    static let dependencies = CodingKeys(stringValue: "dependencies")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "id",
      "projectId",
      "status",
      "statusDetail",
      "source",
      "steps",
      "results",
      "createTime",
      "startTime",
      "finishTime",
      "timeout",
      "images",
      "queueTtl",
      "artifacts",
      "logsBucket",
      "sourceProvenance",
      "buildTriggerId",
      "options",
      "logUrl",
      "substitutions",
      "tags",
      "secrets",
      "timing",
      "approval",
      "serviceAccount",
      "availableSecrets",
      "warnings",
      "gitConfig",
      "failureInfo",
      "dependencies",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .id) {
      self.id = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .projectId) {
      self.projectId = value
    }
    if let value = try container.decodeIfPresent(Build.Status.self, forKey: .status) {
      self.status = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .statusDetail) {
      self.statusDetail = value
    }
    self.source = try container.decodeIfPresent(Source.self, forKey: .source)
    if let value = try container.decodeIfPresent([BuildStep].self, forKey: .steps) {
      self.steps = value
    }
    self.results = try container.decodeIfPresent(Results.self, forKey: .results)
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.startTime = try container.decodeIfPresent(GoogleWKT.WKTTimestamp.self, forKey: .startTime)
    self.finishTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .finishTime)
    self.timeout = try container.decodeIfPresent(GoogleWKT.WKTDuration.self, forKey: .timeout)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .images) {
      self.images = value
    }
    self.queueTtl = try container.decodeIfPresent(GoogleWKT.WKTDuration.self, forKey: .queueTtl)
    self.artifacts = try container.decodeIfPresent(Artifacts.self, forKey: .artifacts)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .logsBucket) {
      self.logsBucket = value
    }
    self.sourceProvenance = try container.decodeIfPresent(
      SourceProvenance.self, forKey: .sourceProvenance)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .buildTriggerId) {
      self.buildTriggerId = value
    }
    self.options = try container.decodeIfPresent(BuildOptions.self, forKey: .options)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .logUrl) {
      self.logUrl = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .substitutions)
    {
      self.substitutions = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .tags) {
      self.tags = value
    }
    if let value = try container.decodeIfPresent([Secret].self, forKey: .secrets) {
      self.secrets = value
    }
    if let value = try container.decodeIfPresent([Swift.String: TimeSpan].self, forKey: .timing) {
      self.timing = value
    }
    self.approval = try container.decodeIfPresent(BuildApproval.self, forKey: .approval)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceAccount) {
      self.serviceAccount = value
    }
    self.availableSecrets = try container.decodeIfPresent(Secrets.self, forKey: .availableSecrets)
    if let value = try container.decodeIfPresent([Build.Warning].self, forKey: .warnings) {
      self.warnings = value
    }
    self.gitConfig = try container.decodeIfPresent(GitConfig.self, forKey: .gitConfig)
    self.failureInfo = try container.decodeIfPresent(Build.FailureInfo.self, forKey: .failureInfo)
    if let value = try container.decodeIfPresent([Dependency].self, forKey: .dependencies) {
      self.dependencies = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.id, forKey: .id)
    try container.encode(self.projectId, forKey: .projectId)
    try container.encode(self.status, forKey: .status)
    try container.encode(self.statusDetail, forKey: .statusDetail)
    try container.encodeIfPresent(self.source, forKey: .source)
    try container.encode(self.steps, forKey: .steps)
    try container.encodeIfPresent(self.results, forKey: .results)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.startTime, forKey: .startTime)
    try container.encodeIfPresent(self.finishTime, forKey: .finishTime)
    try container.encodeIfPresent(self.timeout, forKey: .timeout)
    try container.encode(self.images, forKey: .images)
    try container.encodeIfPresent(self.queueTtl, forKey: .queueTtl)
    try container.encodeIfPresent(self.artifacts, forKey: .artifacts)
    try container.encode(self.logsBucket, forKey: .logsBucket)
    try container.encodeIfPresent(self.sourceProvenance, forKey: .sourceProvenance)
    try container.encode(self.buildTriggerId, forKey: .buildTriggerId)
    try container.encodeIfPresent(self.options, forKey: .options)
    try container.encode(self.logUrl, forKey: .logUrl)
    try container.encode(self.substitutions, forKey: .substitutions)
    try container.encode(self.tags, forKey: .tags)
    try container.encode(self.secrets, forKey: .secrets)
    try container.encode(self.timing, forKey: .timing)
    try container.encodeIfPresent(self.approval, forKey: .approval)
    try container.encode(self.serviceAccount, forKey: .serviceAccount)
    try container.encodeIfPresent(self.availableSecrets, forKey: .availableSecrets)
    try container.encode(self.warnings, forKey: .warnings)
    try container.encodeIfPresent(self.gitConfig, forKey: .gitConfig)
    try container.encodeIfPresent(self.failureInfo, forKey: .failureInfo)
    try container.encode(self.dependencies, forKey: .dependencies)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// A non-fatal problem encountered during the execution of the build.
  public struct Warning: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Explanation of the warning generated.
    public var text: Swift.String = Swift.String()

    /// The priority for this warning.
    public var priority: Build.Warning.Priority = Build.Warning.Priority()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Warning`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Warning().with { $0.text = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let text = CodingKeys(stringValue: "text")
      static let priority = CodingKeys(stringValue: "priority")

      static let _knownKeys: Set<Swift.String> = [
        "text",
        "priority",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .text) {
        self.text = value
      }
      if let value = try container.decodeIfPresent(Build.Warning.Priority.self, forKey: .priority) {
        self.priority = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.text, forKey: .text)
      try container.encode(self.priority, forKey: .priority)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The relative importance of this warning.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum Priority: Codable, Equatable, Hashable, Sendable {
      /// Should not be used.
      case unspecified
      /// e.g. deprecation warnings and alternative feature highlights.
      case info
      /// e.g. automated detection of possible issues with the build.
      case warning
      /// e.g. alerts that a feature used in the build is pending removal
      case alert
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .info: return 1
        case .warning: return 2
        case .alert: return 3
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "PRIORITY_UNSPECIFIED"
        case .info: return "INFO"
        case .warning: return "WARNING"
        case .alert: return "ALERT"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Priority/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "PRIORITY_UNSPECIFIED": self = .unspecified
        case "INFO": self = .info
        case "WARNING": self = .warning
        case "ALERT": self = .alert
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Priority/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .info
        case 2: self = .warning
        case 3: self = .alert
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("PRIORITY_UNSPECIFIED")
        case .info: return try container.encode("INFO")
        case .warning: return try container.encode("WARNING")
        case .alert: return try container.encode("ALERT")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.devtools.cloudbuild.v1.Build.Warning"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// A fatal problem encountered during the execution of the build.
  public struct FailureInfo: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The name of the failure.
    public var type: Build.FailureInfo.FailureType = Build.FailureInfo.FailureType()

    /// Explains the failure issue in more detail using hard-coded text.
    public var detail: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `FailureInfo`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = FailureInfo().with { $0.type = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let type = CodingKeys(stringValue: "type")
      static let detail = CodingKeys(stringValue: "detail")

      static let _knownKeys: Set<Swift.String> = [
        "type",
        "detail",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        Build.FailureInfo.FailureType.self, forKey: .type)
      {
        self.type = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .detail) {
        self.detail = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.type, forKey: .type)
      try container.encode(self.detail, forKey: .detail)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The name of a fatal problem encountered during the execution of the
    /// build.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum FailureType: Codable, Equatable, Hashable, Sendable {
      /// Type unspecified
      case unspecified
      /// Unable to push the image to the repository.
      case pushFailed
      /// Final image not found.
      case pushImageNotFound
      /// Unauthorized push of the final image.
      case pushNotAuthorized
      /// Backend logging failures. Should retry.
      case loggingFailure
      /// A build step has failed.
      case userBuildStep
      /// The source fetching has failed.
      case fetchSourceFailed
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .pushFailed: return 1
        case .pushImageNotFound: return 2
        case .pushNotAuthorized: return 3
        case .loggingFailure: return 4
        case .userBuildStep: return 5
        case .fetchSourceFailed: return 6
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "FAILURE_TYPE_UNSPECIFIED"
        case .pushFailed: return "PUSH_FAILED"
        case .pushImageNotFound: return "PUSH_IMAGE_NOT_FOUND"
        case .pushNotAuthorized: return "PUSH_NOT_AUTHORIZED"
        case .loggingFailure: return "LOGGING_FAILURE"
        case .userBuildStep: return "USER_BUILD_STEP"
        case .fetchSourceFailed: return "FETCH_SOURCE_FAILED"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:FailureType/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "FAILURE_TYPE_UNSPECIFIED": self = .unspecified
        case "PUSH_FAILED": self = .pushFailed
        case "PUSH_IMAGE_NOT_FOUND": self = .pushImageNotFound
        case "PUSH_NOT_AUTHORIZED": self = .pushNotAuthorized
        case "LOGGING_FAILURE": self = .loggingFailure
        case "USER_BUILD_STEP": self = .userBuildStep
        case "FETCH_SOURCE_FAILED": self = .fetchSourceFailed
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:FailureType/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .pushFailed
        case 2: self = .pushImageNotFound
        case 3: self = .pushNotAuthorized
        case 4: self = .loggingFailure
        case 5: self = .userBuildStep
        case 6: self = .fetchSourceFailed
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("FAILURE_TYPE_UNSPECIFIED")
        case .pushFailed: return try container.encode("PUSH_FAILED")
        case .pushImageNotFound: return try container.encode("PUSH_IMAGE_NOT_FOUND")
        case .pushNotAuthorized: return try container.encode("PUSH_NOT_AUTHORIZED")
        case .loggingFailure: return try container.encode("LOGGING_FAILURE")
        case .userBuildStep: return try container.encode("USER_BUILD_STEP")
        case .fetchSourceFailed: return try container.encode("FETCH_SOURCE_FAILED")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.devtools.cloudbuild.v1.Build.FailureInfo"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Possible status of a build or build step.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Status: Codable, Equatable, Hashable, Sendable {
    /// Status of the build is unknown.
    case unknown
    /// Build or step is queued; work has not yet begun.
    case queued
    /// Build or step is being executed.
    case working
    /// Build or step finished successfully.
    case success
    /// Build or step failed to complete successfully.
    case failure
    /// Build or step failed due to an internal cause.
    case internalError
    /// Build or step took longer than was allowed.
    case timeout
    /// Build or step was canceled by a user.
    case cancelled
    /// Build was enqueued for longer than the value of `queue_ttl`.
    case expired
    /// Build has been created and is pending execution and queuing. It has not
    /// been queued.
    case pending
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unknown
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unknown: return 0
      case .queued: return 1
      case .working: return 2
      case .success: return 3
      case .failure: return 4
      case .internalError: return 5
      case .timeout: return 6
      case .cancelled: return 7
      case .expired: return 9
      case .pending: return 10
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unknown: return "STATUS_UNKNOWN"
      case .queued: return "QUEUED"
      case .working: return "WORKING"
      case .success: return "SUCCESS"
      case .failure: return "FAILURE"
      case .internalError: return "INTERNAL_ERROR"
      case .timeout: return "TIMEOUT"
      case .cancelled: return "CANCELLED"
      case .expired: return "EXPIRED"
      case .pending: return "PENDING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Status/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATUS_UNKNOWN": self = .unknown
      case "PENDING": self = .pending
      case "QUEUED": self = .queued
      case "WORKING": self = .working
      case "SUCCESS": self = .success
      case "FAILURE": self = .failure
      case "INTERNAL_ERROR": self = .internalError
      case "TIMEOUT": self = .timeout
      case "CANCELLED": self = .cancelled
      case "EXPIRED": self = .expired
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Status/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unknown
      case 1: self = .queued
      case 2: self = .working
      case 3: self = .success
      case 4: self = .failure
      case 5: self = .internalError
      case 6: self = .timeout
      case 7: self = .cancelled
      case 9: self = .expired
      case 10: self = .pending
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unknown: return try container.encode("STATUS_UNKNOWN")
      case .queued: return try container.encode("QUEUED")
      case .working: return try container.encode("WORKING")
      case .success: return try container.encode("SUCCESS")
      case .failure: return try container.encode("FAILURE")
      case .internalError: return try container.encode("INTERNAL_ERROR")
      case .timeout: return try container.encode("TIMEOUT")
      case .cancelled: return try container.encode("CANCELLED")
      case .expired: return try container.encode("EXPIRED")
      case .pending: return try container.encode("PENDING")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.cloudbuild.v1.Build"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
