// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// An image built by the pipeline.
public struct BuiltImage: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Name used to push the container image to Google Container Registry, as
  /// presented to `docker push`.
  public var name: Swift.String = Swift.String()

  /// Docker Registry 2.0 digest.
  public var digest: Swift.String = Swift.String()

  /// Output only. Stores timing information for pushing the specified image.
  public var pushTiming: TimeSpan? = nil

  /// Output only. Path to the artifact in Artifact Registry.
  public var artifactRegistryPackage: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BuiltImage`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BuiltImage().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let digest = CodingKeys(stringValue: "digest")
    static let pushTiming = CodingKeys(stringValue: "pushTiming")
    static let artifactRegistryPackage = CodingKeys(stringValue: "artifactRegistryPackage")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "digest",
      "pushTiming",
      "artifactRegistryPackage",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .digest) {
      self.digest = value
    }
    self.pushTiming = try container.decodeIfPresent(TimeSpan.self, forKey: .pushTiming)
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .artifactRegistryPackage)
    {
      self.artifactRegistryPackage = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.digest, forKey: .digest)
    try container.encodeIfPresent(self.pushTiming, forKey: .pushTiming)
    try container.encode(self.artifactRegistryPackage, forKey: .artifactRegistryPackage)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.cloudbuild.v1.BuiltImage"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
