// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// An image built by the pipeline.
public struct BuiltImage: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Name used to push the container image to Google Container Registry, as
  /// presented to `docker push`.
  public var name: Swift.String = Swift.String()

  /// Docker Registry 2.0 digest.
  public var digest: Swift.String = Swift.String()

  /// Output only. Stores timing information for pushing the specified image.
  public var pushTiming: TimeSpan? = nil

  /// Output only. Path to the artifact in Artifact Registry.
  public var artifactRegistryPackage: Swift.String = Swift.String()

  /// Initialize a new instance of `BuiltImage`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BuiltImage().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.cloudbuild.v1.BuiltImage"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
