// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
@_spi(GoogleCloudInternal) import GoogleCloudGax

extension Clients {
  class CloudBuildTransport: CloudBuildStub {
    let inner: GoogleCloudGax._HTTPClient

    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      self.inner = try GoogleCloudGax._HTTPClient(
        from: options,
        withDefaultEndpoint: "https://cloudbuild.googleapis.com",
      )
    }

    public func createBuild(
      request: CreateBuildRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.projectId as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.project_id' is not set or is empty")
        }
        return "/v1/projects/\(pathVariable0)/builds"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.parent, prefix: "parent"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.build {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getBuild(
      request: GetBuildRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBuildV1.Build {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.projectId as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.project_id' is not set or is empty")
        }
        guard let pathVariable1 = request.id as Swift.String?, !pathVariable1.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.id' is not set or is empty")
        }
        return "/v1/projects/\(pathVariable0)/builds/\(pathVariable1)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.name, prefix: "name"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudBuildV1.Build.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listBuilds(
      request: ListBuildsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBuildV1.ListBuildsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.projectId as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.project_id' is not set or is empty")
        }
        return "/v1/projects/\(pathVariable0)/builds"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.parent, prefix: "parent"))
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudBuildV1.ListBuildsResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func cancelBuild(
      request: CancelBuildRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBuildV1.Build {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.projectId as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.project_id' is not set or is empty")
        }
        guard let pathVariable1 = request.id as Swift.String?, !pathVariable1.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.id' is not set or is empty")
        }
        return "/v1/projects/\(pathVariable0)/builds/\(pathVariable1):cancel"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      req.setBody(data: try JSONEncoder().encode(request), ofContentType: "application/json")
      return try await req.rpc(
        GoogleCloudBuildV1.Build.self, timeout: options.attemptTimeout
      ).get()
    }

    public func retryBuild(
      request: RetryBuildRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.projectId as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.project_id' is not set or is empty")
        }
        guard let pathVariable1 = request.id as Swift.String?, !pathVariable1.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.id' is not set or is empty")
        }
        return "/v1/projects/\(pathVariable0)/builds/\(pathVariable1):retry"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      req.setBody(data: try JSONEncoder().encode(request), ofContentType: "application/json")
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func approveBuild(
      request: ApproveBuildRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0):approve"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      req.setBody(data: try JSONEncoder().encode(request), ofContentType: "application/json")
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func createBuildTrigger(
      request: CreateBuildTriggerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBuildV1.BuildTrigger {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.projectId as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.project_id' is not set or is empty")
        }
        return "/v1/projects/\(pathVariable0)/triggers"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.parent, prefix: "parent"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.trigger {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleCloudBuildV1.BuildTrigger.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getBuildTrigger(
      request: GetBuildTriggerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBuildV1.BuildTrigger {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.projectId as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.project_id' is not set or is empty")
        }
        guard let pathVariable1 = request.triggerId as Swift.String?, !pathVariable1.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.trigger_id' is not set or is empty")
        }
        return "/v1/projects/\(pathVariable0)/triggers/\(pathVariable1)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.name, prefix: "name"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudBuildV1.BuildTrigger.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listBuildTriggers(
      request: ListBuildTriggersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBuildV1.ListBuildTriggersResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.projectId as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.project_id' is not set or is empty")
        }
        return "/v1/projects/\(pathVariable0)/triggers"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.parent, prefix: "parent"))
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudBuildV1.ListBuildTriggersResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func deleteBuildTrigger(
      request: DeleteBuildTriggerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.projectId as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.project_id' is not set or is empty")
        }
        guard let pathVariable1 = request.triggerId as Swift.String?, !pathVariable1.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.trigger_id' is not set or is empty")
        }
        return "/v1/projects/\(pathVariable0)/triggers/\(pathVariable1)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.name, prefix: "name"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.DELETE)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      _ = try await req.rpc(
        GoogleCloudWkt.Empty.self, timeout: options.attemptTimeout
      ).get()
    }

    public func updateBuildTrigger(
      request: UpdateBuildTriggerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBuildV1.BuildTrigger {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.projectId as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.project_id' is not set or is empty")
        }
        guard let pathVariable1 = request.triggerId as Swift.String?, !pathVariable1.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.trigger_id' is not set or is empty")
        }
        return "/v1/projects/\(pathVariable0)/triggers/\(pathVariable1)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.PATCH)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.trigger {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleCloudBuildV1.BuildTrigger.self, timeout: options.attemptTimeout
      ).get()
    }

    public func runBuildTrigger(
      request: RunBuildTriggerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.projectId as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.project_id' is not set or is empty")
        }
        guard let pathVariable1 = request.triggerId as Swift.String?, !pathVariable1.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.trigger_id' is not set or is empty")
        }
        return "/v1/projects/\(pathVariable0)/triggers/\(pathVariable1):run"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.name, prefix: "name"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.source {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func receiveTriggerWebhook(
      request: ReceiveTriggerWebhookRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBuildV1.ReceiveTriggerWebhookResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.projectId as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.project_id' is not set or is empty")
        }
        guard let pathVariable1 = request.trigger as Swift.String?, !pathVariable1.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.trigger' is not set or is empty")
        }
        return "/v1/projects/\(pathVariable0)/triggers/\(pathVariable1):webhook"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.name, prefix: "name"))
      query.append(contentsOf: try encoder.encode(request.secret, prefix: "secret"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.body {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleCloudBuildV1.ReceiveTriggerWebhookResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func createWorkerPool(
      request: CreateWorkerPoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/workerPools"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.workerPoolId, prefix: "workerPoolId"))
      query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.workerPool {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getWorkerPool(
      request: GetWorkerPoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBuildV1.WorkerPool {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudBuildV1.WorkerPool.self, timeout: options.attemptTimeout
      ).get()
    }

    public func deleteWorkerPool(
      request: DeleteWorkerPoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.etag, prefix: "etag"))
      query.append(contentsOf: try encoder.encode(request.allowMissing, prefix: "allowMissing"))
      query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.DELETE)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func updateWorkerPool(
      request: UpdateWorkerPoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.workerPool.map({ $0.name }), !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding(
            "'request.worker_pool.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
      query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.PATCH)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.workerPool {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listWorkerPools(
      request: ListWorkerPoolsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBuildV1.ListWorkerPoolsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/workerPools"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudBuildV1.ListWorkerPoolsResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getDefaultServiceAccount(
      request: GetDefaultServiceAccountRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBuildV1.DefaultServiceAccount {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudBuildV1.DefaultServiceAccount.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0):cancel"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      req.setBody(data: try JSONEncoder().encode(request), ofContentType: "application/json")
      _ = try await req.rpc(
        GoogleCloudWkt.Empty.self, timeout: options.attemptTimeout
      ).get()
    }
  }
}
