// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class CloudBuildLogging: CloudBuildStub {
    let inner: any CloudBuildStub
    let logger: Logger

    public init(_ inner: any CloudBuildStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-devtools-cloudbuild-v1"
      logger[metadataKey: "gcp.client.service"] = "cloudbuild"
      logger[metadataKey: "gcp.experimental.swift.client"] = "CloudBuild"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func createBuild(
      request: CreateBuildRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createBuild",
        action: {
          (r: CreateBuildRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createBuild(request: r, options: o)
        })
    }

    public func getBuild(
      request: GetBuildRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBuildV1.Build {
      try await self._intercept(
        request: request,
        options: options,
        name: "getBuild",
        action: {
          (r: GetBuildRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBuildV1.Build
          in
          return try await self.inner.getBuild(request: r, options: o)
        })
    }

    public func listBuilds(
      request: ListBuildsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBuildV1.ListBuildsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listBuilds",
        action: {
          (r: ListBuildsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBuildV1.ListBuildsResponse
          in
          return try await self.inner.listBuilds(request: r, options: o)
        })
    }

    public func cancelBuild(
      request: CancelBuildRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBuildV1.Build {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelBuild",
        action: {
          (r: CancelBuildRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBuildV1.Build
          in
          return try await self.inner.cancelBuild(request: r, options: o)
        })
    }

    public func retryBuild(
      request: RetryBuildRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "retryBuild",
        action: {
          (r: RetryBuildRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.retryBuild(request: r, options: o)
        })
    }

    public func approveBuild(
      request: ApproveBuildRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "approveBuild",
        action: {
          (r: ApproveBuildRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.approveBuild(request: r, options: o)
        })
    }

    public func createBuildTrigger(
      request: CreateBuildTriggerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBuildV1.BuildTrigger {
      try await self._intercept(
        request: request,
        options: options,
        name: "createBuildTrigger",
        action: {
          (r: CreateBuildTriggerRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBuildV1.BuildTrigger
          in
          return try await self.inner.createBuildTrigger(request: r, options: o)
        })
    }

    public func getBuildTrigger(
      request: GetBuildTriggerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBuildV1.BuildTrigger {
      try await self._intercept(
        request: request,
        options: options,
        name: "getBuildTrigger",
        action: {
          (r: GetBuildTriggerRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBuildV1.BuildTrigger
          in
          return try await self.inner.getBuildTrigger(request: r, options: o)
        })
    }

    public func listBuildTriggers(
      request: ListBuildTriggersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBuildV1.ListBuildTriggersResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listBuildTriggers",
        action: {
          (r: ListBuildTriggersRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBuildV1.ListBuildTriggersResponse
          in
          return try await self.inner.listBuildTriggers(request: r, options: o)
        })
    }

    public func deleteBuildTrigger(
      request: DeleteBuildTriggerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteBuildTrigger",
        action: {
          (r: DeleteBuildTriggerRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteBuildTrigger(request: r, options: o)
        })
    }

    public func updateBuildTrigger(
      request: UpdateBuildTriggerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBuildV1.BuildTrigger {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateBuildTrigger",
        action: {
          (r: UpdateBuildTriggerRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBuildV1.BuildTrigger
          in
          return try await self.inner.updateBuildTrigger(request: r, options: o)
        })
    }

    public func runBuildTrigger(
      request: RunBuildTriggerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "runBuildTrigger",
        action: {
          (r: RunBuildTriggerRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.runBuildTrigger(request: r, options: o)
        })
    }

    public func receiveTriggerWebhook(
      request: ReceiveTriggerWebhookRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBuildV1.ReceiveTriggerWebhookResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "receiveTriggerWebhook",
        action: {
          (r: ReceiveTriggerWebhookRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBuildV1.ReceiveTriggerWebhookResponse
          in
          return try await self.inner.receiveTriggerWebhook(request: r, options: o)
        })
    }

    public func createWorkerPool(
      request: CreateWorkerPoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createWorkerPool",
        action: {
          (r: CreateWorkerPoolRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createWorkerPool(request: r, options: o)
        })
    }

    public func getWorkerPool(
      request: GetWorkerPoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBuildV1.WorkerPool {
      try await self._intercept(
        request: request,
        options: options,
        name: "getWorkerPool",
        action: {
          (r: GetWorkerPoolRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBuildV1.WorkerPool
          in
          return try await self.inner.getWorkerPool(request: r, options: o)
        })
    }

    public func deleteWorkerPool(
      request: DeleteWorkerPoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteWorkerPool",
        action: {
          (r: DeleteWorkerPoolRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteWorkerPool(request: r, options: o)
        })
    }

    public func updateWorkerPool(
      request: UpdateWorkerPoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateWorkerPool",
        action: {
          (r: UpdateWorkerPoolRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateWorkerPool(request: r, options: o)
        })
    }

    public func listWorkerPools(
      request: ListWorkerPoolsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBuildV1.ListWorkerPoolsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listWorkerPools",
        action: {
          (r: ListWorkerPoolsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBuildV1.ListWorkerPoolsResponse
          in
          return try await self.inner.listWorkerPools(request: r, options: o)
        })
    }

    public func getDefaultServiceAccount(
      request: GetDefaultServiceAccountRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBuildV1.DefaultServiceAccount {
      try await self._intercept(
        request: request,
        options: options,
        name: "getDefaultServiceAccount",
        action: {
          (r: GetDefaultServiceAccountRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBuildV1.DefaultServiceAccount
          in
          return try await self.inner.getDefaultServiceAccount(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
