// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

extension Clients {
  protocol CloudBuildStub {
    func createBuild(
      request: CreateBuildRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getBuild(
      request: GetBuildRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBuildV1.Build

    func listBuilds(
      request: ListBuildsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBuildV1.ListBuildsResponse

    func cancelBuild(
      request: CancelBuildRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBuildV1.Build

    func retryBuild(
      request: RetryBuildRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func approveBuild(
      request: ApproveBuildRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func createBuildTrigger(
      request: CreateBuildTriggerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBuildV1.BuildTrigger

    func getBuildTrigger(
      request: GetBuildTriggerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBuildV1.BuildTrigger

    func listBuildTriggers(
      request: ListBuildTriggersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBuildV1.ListBuildTriggersResponse

    func deleteBuildTrigger(
      request: DeleteBuildTriggerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func updateBuildTrigger(
      request: UpdateBuildTriggerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBuildV1.BuildTrigger

    func runBuildTrigger(
      request: RunBuildTriggerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func receiveTriggerWebhook(
      request: ReceiveTriggerWebhookRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBuildV1.ReceiveTriggerWebhookResponse

    func createWorkerPool(
      request: CreateWorkerPoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getWorkerPool(
      request: GetWorkerPoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBuildV1.WorkerPool

    func deleteWorkerPool(
      request: DeleteWorkerPoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateWorkerPool(
      request: UpdateWorkerPoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listWorkerPools(
      request: ListWorkerPoolsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBuildV1.ListWorkerPoolsResponse

    func getDefaultServiceAccount(
      request: GetDefaultServiceAccountRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBuildV1.DefaultServiceAccount

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}
