// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Request to create a new `WorkerPool`.
public struct CreateWorkerPoolRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The parent resource where this worker pool will be created.
  /// Format: `projects/{project}/locations/{location}`.
  public var parent: Swift.String = Swift.String()

  /// Required. `WorkerPool` resource to create.
  public var workerPool: WorkerPool? = nil

  /// Required. Immutable. The ID to use for the `WorkerPool`, which will become
  /// the final component of the resource name.
  ///
  /// This value should be 1-63 characters, and valid characters
  /// are /[a-z][0-9]-/.
  public var workerPoolId: Swift.String = Swift.String()

  /// If set, validate the request and preview the response, but do not actually
  /// post it.
  public var validateOnly: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `CreateWorkerPoolRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateWorkerPoolRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.cloudbuild.v1.CreateWorkerPoolRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
