// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The default service account used for `Builds`.
public struct DefaultServiceAccount: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. Format:
  /// `projects/{project}/locations/{location}/defaultServiceAccount`
  public var name: Swift.String = Swift.String()

  /// Output only. The email address of the service account identity that will be
  /// used for a build by default.
  ///
  /// This is returned in the format
  /// `projects/{project}/serviceAccounts/{service_account}` where
  /// `{service_account}` could be the legacy Cloud Build SA, in the format
  /// [PROJECT_NUMBER]@cloudbuild.gserviceaccount.com or the Compute SA, in the
  /// format [PROJECT_NUMBER]-compute@developer.gserviceaccount.com.
  ///
  /// If no service account will be used by default, this will be empty.
  public var serviceAccountEmail: Swift.String = Swift.String()

  /// Initialize a new instance of `DefaultServiceAccount`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DefaultServiceAccount().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.cloudbuild.v1.DefaultServiceAccount"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
