// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A dependency that the Cloud Build worker will fetch before executing user
/// steps.
public struct Dependency: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The type of dependency to fetch.
  public var dep: OneOf_Dep? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Dependency`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Dependency().with { $0.empty = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let empty = CodingKeys(stringValue: "empty")
    static let gitSource = CodingKeys(stringValue: "gitSource")

    static let _knownKeys: Set<Swift.String> = [
      "empty",
      "gitSource",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var dep: OneOf_Dep? = nil
    let depCheckAndSet = {
      if dep != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'dep'")
        )
      }
      dep = $0
    }
    if let empty = try container.decodeIfPresent(Swift.Bool.self, forKey: .empty) {
      try depCheckAndSet(.empty(empty))
    }
    if let gitSource = try container.decodeIfPresent(
      Dependency.GitSourceDependency?.self, forKey: .gitSource)
    {
      try depCheckAndSet(.gitSource(gitSource))
    }
    self.dep = dep
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.dep {
      switch choice {
      case .empty(let value):
        try container.encode(value, forKey: .empty)
      case .gitSource(let value):
        try container.encode(value, forKey: .gitSource)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Represents a git repository as a build dependency.
  public struct GitSourceDependency: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. The kind of repo (url or dev connect).
    public var repository: Dependency.GitSourceRepository? = nil

    /// Required. The revision that we will fetch the repo at.
    public var revision: Swift.String = Swift.String()

    /// Optional. True if submodules should be fetched too (default false).
    public var recurseSubmodules: Swift.Bool = Swift.Bool()

    /// Optional. How much history should be fetched for the build (default 1, -1
    /// for all history).
    public var depth: Swift.Int64 = Swift.Int64()

    /// Required. Where should the files be placed on the worker.
    public var destPath: Swift.String = Swift.String()

    /// Optional. True if remote tags should be fetched too (default false).
    /// Note: when depth is 1 (default), git fetch only retrieves tags pointing
    /// to commits within the shallow boundary. Set depth to -1 to fetch all
    /// historical tags.
    public var fetchTags: Swift.Bool = Swift.Bool()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `GitSourceDependency`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GitSourceDependency().with { $0.repository = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let repository = CodingKeys(stringValue: "repository")
      static let revision = CodingKeys(stringValue: "revision")
      static let recurseSubmodules = CodingKeys(stringValue: "recurseSubmodules")
      static let depth = CodingKeys(stringValue: "depth")
      static let destPath = CodingKeys(stringValue: "destPath")
      static let fetchTags = CodingKeys(stringValue: "fetchTags")

      static let _knownKeys: Set<Swift.String> = [
        "repository",
        "revision",
        "recurseSubmodules",
        "depth",
        "destPath",
        "fetchTags",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.repository = try container.decodeIfPresent(
        Dependency.GitSourceRepository.self, forKey: .repository)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .revision) {
        self.revision = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .recurseSubmodules) {
        self.recurseSubmodules = value
      }
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .depth) {
        self.depth = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .destPath) {
        self.destPath = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .fetchTags) {
        self.fetchTags = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.repository, forKey: .repository)
      try container.encode(self.revision, forKey: .revision)
      try container.encode(self.recurseSubmodules, forKey: .recurseSubmodules)
      try container.encode(self.depth, forKey: .depth)
      try container.encode(self.destPath, forKey: .destPath)
      try container.encode(self.fetchTags, forKey: .fetchTags)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.devtools.cloudbuild.v1.Dependency.GitSourceDependency"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// A repository for a git source.
  public struct GitSourceRepository: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The type of git source repo (url or dev connect).
    public var repotype: OneOf_Repotype? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `GitSourceRepository`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GitSourceRepository().with { $0.url = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let url = CodingKeys(stringValue: "url")
      static let developerConnect = CodingKeys(stringValue: "developerConnect")

      static let _knownKeys: Set<Swift.String> = [
        "url",
        "developerConnect",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var repotype: OneOf_Repotype? = nil
      let repotypeCheckAndSet = {
        if repotype != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'repotype'"))
        }
        repotype = $0
      }
      if let url = try container.decodeIfPresent(Swift.String.self, forKey: .url) {
        try repotypeCheckAndSet(.url(url))
      }
      if let developerConnect = try container.decodeIfPresent(
        Swift.String.self, forKey: .developerConnect)
      {
        try repotypeCheckAndSet(.developerConnect(developerConnect))
      }
      self.repotype = repotype
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.repotype {
        switch choice {
        case .url(let value):
          try container.encode(value, forKey: .url)
        case .developerConnect(let value):
          try container.encode(value, forKey: .developerConnect)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The type of git source repo (url or dev connect).
    public enum OneOf_Repotype: Codable, Equatable, Sendable {
      /// Location of the Git repository.
      case url(Swift.String)
      /// The Developer Connect Git repository link formatted as
      /// `projects/*/locations/*/connections/*/gitRepositoryLink/*`
      case developerConnect(Swift.String)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.devtools.cloudbuild.v1.Dependency.GitSourceRepository"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The type of dependency to fetch.
  public enum OneOf_Dep: Codable, Equatable, Sendable {
    /// If set to true disable all dependency fetching (ignoring the default
    /// source as well).
    case empty(Swift.Bool)
    /// Represents a git repository as a build dependency.
    indirect case gitSource(Dependency.GitSourceDependency?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.cloudbuild.v1.Dependency"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
