// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// GitConfig is a configuration for git operations.
public struct GitConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Configuration for HTTP related git operations.
  public var http: GitConfig.HttpConfig? = nil

  /// Initialize a new instance of `GitConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GitConfig().with { $0.http = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// HttpConfig is a configuration for HTTP related git operations.
  public struct HttpConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// SecretVersion resource of the HTTP proxy URL. The Service Account used in
    /// the build (either the default Service Account or
    /// user-specified Service Account) should have
    /// `secretmanager.versions.access` permissions on this secret. The proxy URL
    /// should be in format `[protocol://][user[:password]@]proxyhost[:port]`.
    public var proxySecretVersionName: Swift.String = Swift.String()

    /// Initialize a new instance of `HttpConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = HttpConfig().with { $0.proxySecretVersionName = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.devtools.cloudbuild.v1.GitConfig.HttpConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.cloudbuild.v1.GitConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
