// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// GitFileSource describes a file within a (possibly remote) code repository.
public struct GitFileSource: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The path of the file, with the repo root as the root of the path.
  public var path: Swift.String = Swift.String()

  /// The URI of the repo.
  /// Either uri or repository can be specified.
  /// If unspecified, the repo from which the trigger invocation originated is
  /// assumed to be the repo from which to read the specified path.
  public var uri: Swift.String = Swift.String()

  /// See RepoType above.
  public var repoType: GitFileSource.RepoType = GitFileSource.RepoType()

  /// The branch, tag, arbitrary ref, or SHA version of the repo to use when
  /// resolving the filename (optional).
  /// This field respects the same syntax/resolution as described here:
  /// https://git-scm.com/docs/gitrevisions
  /// If unspecified, the revision from which the trigger invocation originated
  /// is assumed to be the revision from which to read the specified path.
  public var revision: Swift.String = Swift.String()

  /// The source of the SCM repo.
  public var source: OneOf_Source? = nil

  /// The resource name of the enterprise config that should be applied
  /// to this source.
  public var enterpriseConfig: OneOf_EnterpriseConfig? = nil

  /// Initialize a new instance of `GitFileSource`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GitFileSource().with { $0.path = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case path = "path"
    case uri = "uri"
    case repository = "repository"
    case repoType = "repoType"
    case revision = "revision"
    case githubEnterpriseConfig = "githubEnterpriseConfig"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.path = try container.decode(Swift.String.self, forKey: .path)
    self.uri = try container.decode(Swift.String.self, forKey: .uri)
    self.repoType = try container.decode(GitFileSource.RepoType.self, forKey: .repoType)
    self.revision = try container.decode(Swift.String.self, forKey: .revision)

    var source: OneOf_Source? = nil
    let sourceCheckAndSet = {
      if source != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'source'"))
      }
      source = $0
    }
    if let repository = try container.decodeIfPresent(Swift.String.self, forKey: .repository) {
      try sourceCheckAndSet(.repository(repository))
    }
    self.source = source

    var enterpriseConfig: OneOf_EnterpriseConfig? = nil
    let enterpriseConfigCheckAndSet = {
      if enterpriseConfig != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'enterpriseConfig'"))
      }
      enterpriseConfig = $0
    }
    if let githubEnterpriseConfig = try container.decodeIfPresent(
      Swift.String.self, forKey: .githubEnterpriseConfig)
    {
      try enterpriseConfigCheckAndSet(.githubEnterpriseConfig(githubEnterpriseConfig))
    }
    self.enterpriseConfig = enterpriseConfig
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.path, forKey: .path)
    try container.encode(self.uri, forKey: .uri)
    try container.encode(self.repoType, forKey: .repoType)
    try container.encode(self.revision, forKey: .revision)

    if let choice = self.source {
      switch choice {
      case .repository(let value):
        try container.encode(value, forKey: .repository)
      }
    }

    if let choice = self.enterpriseConfig {
      switch choice {
      case .githubEnterpriseConfig(let value):
        try container.encode(value, forKey: .githubEnterpriseConfig)
      }
    }
  }

  /// The type of the repo, since it may not be explicit from the `repo` field
  /// (e.g from a URL).
  public enum RepoType: Codable, Equatable, Sendable {
    /// The default, unknown repo type. Don't use it, instead use one of
    /// the other repo types.
    case unknown
    /// A Google Cloud Source Repositories-hosted repo.
    case cloudSourceRepositories
    /// A GitHub-hosted repo not necessarily on "github.com" (i.e. GitHub
    /// Enterprise).
    case github
    /// A Bitbucket Server-hosted repo.
    case bitbucketServer
    /// A GitLab-hosted repo.
    case gitlab
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unknown
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unknown: return 0
      case .cloudSourceRepositories: return 1
      case .github: return 2
      case .bitbucketServer: return 3
      case .gitlab: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unknown: return "UNKNOWN"
      case .cloudSourceRepositories: return "CLOUD_SOURCE_REPOSITORIES"
      case .github: return "GITHUB"
      case .bitbucketServer: return "BITBUCKET_SERVER"
      case .gitlab: return "GITLAB"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:RepoType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "UNKNOWN": self = .unknown
      case "CLOUD_SOURCE_REPOSITORIES": self = .cloudSourceRepositories
      case "GITHUB": self = .github
      case "BITBUCKET_SERVER": self = .bitbucketServer
      case "GITLAB": self = .gitlab
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:RepoType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unknown
      case 1: self = .cloudSourceRepositories
      case 2: self = .github
      case 3: self = .bitbucketServer
      case 4: self = .gitlab
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unknown: return try container.encode(0)
      case .cloudSourceRepositories: return try container.encode(1)
      case .github: return try container.encode(2)
      case .bitbucketServer: return try container.encode(3)
      case .gitlab: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The source of the SCM repo.
  public enum OneOf_Source: Codable, Equatable, Sendable {
    /// The fully qualified resource name of the Repos API repository.
    /// Either URI or repository can be specified.
    /// If unspecified, the repo from which the trigger invocation originated is
    /// assumed to be the repo from which to read the specified path.
    case repository(Swift.String)
  }

  /// The resource name of the enterprise config that should be applied
  /// to this source.
  public enum OneOf_EnterpriseConfig: Codable, Equatable, Sendable {
    /// The full resource name of the github enterprise config.
    /// Format:
    /// `projects/{project}/locations/{location}/githubEnterpriseConfigs/{id}`.
    /// `projects/{project}/githubEnterpriseConfigs/{id}`.
    case githubEnterpriseConfig(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.cloudbuild.v1.GitFileSource"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
