// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// GitHubEnterpriseSecrets represents the names of all necessary secrets in
/// Secret Manager for a GitHub Enterprise server.
/// Format is: projects/<project number>/secrets/<secret name>.
public struct GitHubEnterpriseSecrets: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The resource name for the private key secret version.
  public var privateKeyVersionName: Swift.String = Swift.String()

  /// The resource name for the webhook secret secret version in Secret Manager.
  public var webhookSecretVersionName: Swift.String = Swift.String()

  /// The resource name for the OAuth secret secret version in Secret Manager.
  public var oauthSecretVersionName: Swift.String = Swift.String()

  /// The resource name for the OAuth client ID secret version in Secret Manager.
  public var oauthClientIdVersionName: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `GitHubEnterpriseSecrets`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GitHubEnterpriseSecrets().with { $0.privateKeyVersionName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let privateKeyVersionName = CodingKeys(stringValue: "privateKeyVersionName")
    static let webhookSecretVersionName = CodingKeys(stringValue: "webhookSecretVersionName")
    static let oauthSecretVersionName = CodingKeys(stringValue: "oauthSecretVersionName")
    static let oauthClientIdVersionName = CodingKeys(stringValue: "oauthClientIdVersionName")

    static let _knownKeys: Set<Swift.String> = [
      "privateKeyVersionName",
      "webhookSecretVersionName",
      "oauthSecretVersionName",
      "oauthClientIdVersionName",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .privateKeyVersionName)
    {
      self.privateKeyVersionName = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .webhookSecretVersionName)
    {
      self.webhookSecretVersionName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .oauthSecretVersionName)
    {
      self.oauthSecretVersionName = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .oauthClientIdVersionName)
    {
      self.oauthClientIdVersionName = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.privateKeyVersionName, forKey: .privateKeyVersionName)
    try container.encode(self.webhookSecretVersionName, forKey: .webhookSecretVersionName)
    try container.encode(self.oauthSecretVersionName, forKey: .oauthSecretVersionName)
    try container.encode(self.oauthClientIdVersionName, forKey: .oauthClientIdVersionName)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.cloudbuild.v1.GitHubEnterpriseSecrets"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
