// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// GitHubEnterpriseConfig represents a configuration for a GitHub Enterprise
/// server.
public struct GitHubEnterpriseConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The full resource name for the GitHubEnterpriseConfig
  /// For example:
  /// "projects/{$project_id}/locations/{$location_id}/githubEnterpriseConfigs/{$config_id}"
  public var name: Swift.String = Swift.String()

  /// The URL of the github enterprise host the configuration is for.
  public var hostUrl: Swift.String = Swift.String()

  /// Required. The GitHub app id of the Cloud Build app on the GitHub Enterprise
  /// server.
  public var appId: Swift.Int64 = Swift.Int64()

  /// Output only. Time when the installation was associated with the project.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// The key that should be attached to webhook calls to the ReceiveWebhook
  /// endpoint.
  public var webhookKey: Swift.String = Swift.String()

  /// Optional. The network to be used when reaching out to the GitHub
  /// Enterprise server. The VPC network must be enabled for private
  /// service connection. This should be set if the GitHub Enterprise server is
  /// hosted on-premises and not reachable by public internet.
  /// If this field is left empty, no network peering will occur and calls to
  /// the GitHub Enterprise server will be made over the public internet.
  /// Must be in the format
  /// `projects/{project}/global/networks/{network}`, where {project}
  /// is a project number or id and {network} is the name of a
  /// VPC network in the project.
  public var peeredNetwork: Swift.String = Swift.String()

  /// Optional. Names of secrets in Secret Manager.
  public var secrets: GitHubEnterpriseSecrets? = nil

  /// Optional. Name to display for this config.
  public var displayName: Swift.String = Swift.String()

  /// Optional. SSL certificate to use for requests to GitHub Enterprise.
  public var sslCa: Swift.String = Swift.String()

  /// Initialize a new instance of `GitHubEnterpriseConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GitHubEnterpriseConfig().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.cloudbuild.v1.GitHubEnterpriseConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
