// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// GitHubEnterpriseSecrets represents the names of all necessary secrets in
/// Secret Manager for a GitHub Enterprise server.
/// Format is: projects/<project number>/secrets/<secret name>.
public struct GitHubEnterpriseSecrets: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The resource name for the private key secret version.
  public var privateKeyVersionName: Swift.String = Swift.String()

  /// The resource name for the webhook secret secret version in Secret Manager.
  public var webhookSecretVersionName: Swift.String = Swift.String()

  /// The resource name for the OAuth secret secret version in Secret Manager.
  public var oauthSecretVersionName: Swift.String = Swift.String()

  /// The resource name for the OAuth client ID secret version in Secret Manager.
  public var oauthClientIdVersionName: Swift.String = Swift.String()

  /// Initialize a new instance of `GitHubEnterpriseSecrets`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GitHubEnterpriseSecrets().with { $0.privateKeyVersionName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.cloudbuild.v1.GitHubEnterpriseSecrets"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
