// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// GitHubEventsConfig describes the configuration of a trigger that creates a
/// build whenever a GitHub event is received.
public struct GitHubEventsConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The installationID that emits the GitHub event.
  @available(*, deprecated)
  public var installationId: Swift.Int64 = Swift.Int64()

  /// Owner of the repository. For example: The owner for
  /// https://github.com/googlecloudplatform/cloud-builders is
  /// "googlecloudplatform".
  public var owner: Swift.String = Swift.String()

  /// Name of the repository. For example: The name for
  /// https://github.com/googlecloudplatform/cloud-builders is "cloud-builders".
  public var name: Swift.String = Swift.String()

  /// Filter describing the types of events to trigger a build.
  /// Currently supported event types: push, pull_request.
  public var event: EventOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `GitHubEventsConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GitHubEventsConfig().with { $0.installationId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let installationId = CodingKeys(stringValue: "installationId")
    static let owner = CodingKeys(stringValue: "owner")
    static let name = CodingKeys(stringValue: "name")
    static let pullRequest = CodingKeys(stringValue: "pullRequest")
    static let push = CodingKeys(stringValue: "push")

    static let _knownKeys: Set<Swift.String> = [
      "installationId",
      "owner",
      "name",
      "pullRequest",
      "push",
    ]
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .installationId) {
      self.installationId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .owner) {
      self.owner = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }

    var event: EventOneOf? = nil
    let eventCheckAndSet = {
      if event != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'event'"))
      }
      event = $0
    }
    if let pullRequest = try container.decodeIfPresent(
      PullRequestFilter?.self, forKey: .pullRequest)
    {
      try eventCheckAndSet(.pullRequest(pullRequest))
    }
    if let push = try container.decodeIfPresent(PushFilter?.self, forKey: .push) {
      try eventCheckAndSet(.push(push))
    }
    self.event = event
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.installationId, forKey: .installationId)
    try container.encode(self.owner, forKey: .owner)
    try container.encode(self.name, forKey: .name)

    if let choice = self.event {
      switch choice {
      case .pullRequest(let value):
        try container.encode(value, forKey: .pullRequest)
      case .push(let value):
        try container.encode(value, forKey: .push)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Filter describing the types of events to trigger a build.
  /// Currently supported event types: push, pull_request.
  public enum EventOneOf: Codable, Equatable, Sendable {
    /// filter to match changes in pull requests.
    indirect case pullRequest(PullRequestFilter?)
    /// filter to match changes in refs like branches, tags.
    indirect case push(PushFilter?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.cloudbuild.v1.GitHubEventsConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
