// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// GitRepoSource describes a repo and ref of a code repository.
public struct GitRepoSource: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The URI of the repo (e.g. https://github.com/user/repo.git).
  /// Either `uri` or `repository` can be specified and is required.
  public var uri: Swift.String = Swift.String()

  /// The branch or tag to use. Must start with "refs/" (required).
  public var ref: Swift.String = Swift.String()

  /// See RepoType below.
  public var repoType: GitFileSource.RepoType = GitFileSource.RepoType()

  /// The source of the SCM repo.
  public var source: OneOf_Source? = nil

  /// The resource name of the enterprise config that should be applied
  /// to this source.
  public var enterpriseConfig: OneOf_EnterpriseConfig? = nil

  /// Initialize a new instance of `GitRepoSource`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GitRepoSource().with { $0.uri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case uri = "uri"
    case repository = "repository"
    case ref = "ref"
    case repoType = "repoType"
    case githubEnterpriseConfig = "githubEnterpriseConfig"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.uri = try container.decode(Swift.String.self, forKey: .uri)
    self.ref = try container.decode(Swift.String.self, forKey: .ref)
    self.repoType = try container.decode(GitFileSource.RepoType.self, forKey: .repoType)

    var source: OneOf_Source? = nil
    let sourceCheckAndSet = {
      if source != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'source'"))
      }
      source = $0
    }
    if let repository = try container.decodeIfPresent(Swift.String.self, forKey: .repository) {
      try sourceCheckAndSet(.repository(repository))
    }
    self.source = source

    var enterpriseConfig: OneOf_EnterpriseConfig? = nil
    let enterpriseConfigCheckAndSet = {
      if enterpriseConfig != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'enterpriseConfig'"))
      }
      enterpriseConfig = $0
    }
    if let githubEnterpriseConfig = try container.decodeIfPresent(
      Swift.String.self, forKey: .githubEnterpriseConfig)
    {
      try enterpriseConfigCheckAndSet(.githubEnterpriseConfig(githubEnterpriseConfig))
    }
    self.enterpriseConfig = enterpriseConfig
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.uri, forKey: .uri)
    try container.encode(self.ref, forKey: .ref)
    try container.encode(self.repoType, forKey: .repoType)

    if let choice = self.source {
      switch choice {
      case .repository(let value):
        try container.encode(value, forKey: .repository)
      }
    }

    if let choice = self.enterpriseConfig {
      switch choice {
      case .githubEnterpriseConfig(let value):
        try container.encode(value, forKey: .githubEnterpriseConfig)
      }
    }
  }

  /// The source of the SCM repo.
  public enum OneOf_Source: Codable, Equatable, Sendable {
    /// The connected repository resource name, in the format
    /// `projects/*/locations/*/connections/*/repositories/*`. Either `uri` or
    /// `repository` can be specified and is required.
    case repository(Swift.String)
  }

  /// The resource name of the enterprise config that should be applied
  /// to this source.
  public enum OneOf_EnterpriseConfig: Codable, Equatable, Sendable {
    /// The full resource name of the github enterprise config.
    /// Format:
    /// `projects/{project}/locations/{location}/githubEnterpriseConfigs/{id}`.
    /// `projects/{project}/githubEnterpriseConfigs/{id}`.
    case githubEnterpriseConfig(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.cloudbuild.v1.GitRepoSource"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
