// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request to list builds.
public struct ListBuildsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The parent of the collection of `Builds`.
  /// Format: `projects/{project}/locations/{location}`
  public var parent: Swift.String = Swift.String()

  /// Required. ID of the project.
  public var projectId: Swift.String = Swift.String()

  /// Number of results to return in the list.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// The page token for the next page of Builds.
  ///
  /// If unspecified, the first page of results is returned.
  ///
  /// If the token is rejected for any reason, INVALID_ARGUMENT will be thrown.
  /// In this case, the token should be discarded, and pagination should be
  /// restarted from the first page of results.
  ///
  /// See https://google.aip.dev/158 for more.
  public var pageToken: Swift.String = Swift.String()

  /// The raw filter text to constrain the results.
  public var filter: Swift.String = Swift.String()

  /// Initialize a new instance of `ListBuildsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListBuildsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.cloudbuild.v1.ListBuildsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
