// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// PubsubConfig describes the configuration of a trigger that
/// creates a build whenever a Pub/Sub message is published.
public struct PubsubConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Name of the subscription. Format is
  /// `projects/{project}/subscriptions/{subscription}`.
  public var subscription: Swift.String = Swift.String()

  /// Optional. The name of the topic from which this subscription is receiving
  /// messages. Format is `projects/{project}/topics/{topic}`.
  public var topic: Swift.String = Swift.String()

  /// Service account that will make the push request.
  public var serviceAccountEmail: Swift.String = Swift.String()

  /// Potential issues with the underlying Pub/Sub subscription configuration.
  /// Only populated on get requests.
  public var state: PubsubConfig.State = PubsubConfig.State()

  /// Initialize a new instance of `PubsubConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PubsubConfig().with { $0.subscription = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Enumerates potential issues with the underlying Pub/Sub subscription
  /// configuration.
  public enum State: Codable, Equatable, Sendable {
    /// The subscription configuration has not been checked.
    case unspecified
    /// The Pub/Sub subscription is properly configured.
    case ok
    /// The subscription has been deleted.
    case subscriptionDeleted
    /// The topic has been deleted.
    case topicDeleted
    /// Some of the subscription's field are misconfigured.
    case subscriptionMisconfigured
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .ok: return 1
      case .subscriptionDeleted: return 2
      case .topicDeleted: return 3
      case .subscriptionMisconfigured: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .ok: return "OK"
      case .subscriptionDeleted: return "SUBSCRIPTION_DELETED"
      case .topicDeleted: return "TOPIC_DELETED"
      case .subscriptionMisconfigured: return "SUBSCRIPTION_MISCONFIGURED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "OK": self = .ok
      case "SUBSCRIPTION_DELETED": self = .subscriptionDeleted
      case "TOPIC_DELETED": self = .topicDeleted
      case "SUBSCRIPTION_MISCONFIGURED": self = .subscriptionMisconfigured
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .ok
      case 2: self = .subscriptionDeleted
      case 3: self = .topicDeleted
      case 4: self = .subscriptionMisconfigured
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .ok: return try container.encode(1)
      case .subscriptionDeleted: return try container.encode(2)
      case .topicDeleted: return try container.encode(3)
      case .subscriptionMisconfigured: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.cloudbuild.v1.PubsubConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
