// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// PullRequestFilter contains filter properties for matching GitHub Pull
/// Requests.
public struct PullRequestFilter: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// If CommentControl is enabled, depending on the setting, builds may not
  /// fire until a repository writer comments `/gcbrun` on a pull
  /// request or `/gcbrun` is in the pull request description.
  /// Only PR comments that contain `/gcbrun` will trigger builds.
  ///
  /// If CommentControl is set to disabled, comments with `/gcbrun` from a user
  /// with repository write permission or above will
  /// still trigger builds to run.
  public var commentControl: PullRequestFilter.CommentControl = PullRequestFilter.CommentControl()

  /// If true, branches that do NOT match the git_ref will trigger a build.
  public var invertRegex: Swift.Bool = Swift.Bool()

  /// Target refs to match.
  /// A target ref is the git reference where the pull request will be applied.
  public var gitRef: OneOf_GitRef? = nil

  /// Initialize a new instance of `PullRequestFilter`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PullRequestFilter().with { $0.branch = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case branch = "branch"
    case commentControl = "commentControl"
    case invertRegex = "invertRegex"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.commentControl = try container.decode(
      PullRequestFilter.CommentControl.self, forKey: .commentControl)
    self.invertRegex = try container.decode(Swift.Bool.self, forKey: .invertRegex)

    var gitRef: OneOf_GitRef? = nil
    let gitRefCheckAndSet = {
      if gitRef != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'gitRef'"))
      }
      gitRef = $0
    }
    if let branch = try container.decodeIfPresent(Swift.String.self, forKey: .branch) {
      try gitRefCheckAndSet(.branch(branch))
    }
    self.gitRef = gitRef
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.commentControl, forKey: .commentControl)
    try container.encode(self.invertRegex, forKey: .invertRegex)

    if let choice = self.gitRef {
      switch choice {
      case .branch(let value):
        try container.encode(value, forKey: .branch)
      }
    }
  }

  /// Controls whether or not a `/gcbrun` comment is required from a user with
  ///  repository write permission or above in order to
  ///  trigger Build runs for pull requests. Pull Request update events differ
  ///  between repo types.
  ///  Check repo specific guides
  /// ([GitHub](https://cloud.google.com/build/docs/automating-builds/github/build-repos-from-github-enterprise#creating_a_github_enterprise_trigger),
  /// [Bitbucket](https://cloud.google.com/build/docs/automating-builds/bitbucket/build-repos-from-bitbucket-server#creating_a_bitbucket_server_trigger),
  /// [GitLab](https://cloud.google.com/build/docs/automating-builds/gitlab/build-repos-from-gitlab#creating_a_gitlab_trigger)
  ///  for details.
  public enum CommentControl: Codable, Equatable, Sendable {
    /// Do not require `/gcbrun` comments from a user with repository write
    /// permission or above on pull requests before builds are triggered.
    /// Comments that contain `/gcbrun` will still fire builds so this should
    /// be thought of as comments not required.
    case commentsDisabled
    /// Builds will only fire in response to pull requests if:
    /// 1. The pull request author has repository write permission or above and
    /// `/gcbrun` is in the PR description.
    /// 2. A user with repository writer permissions or above comments `/gcbrun`
    /// on a pull request authored by any user.
    case commentsEnabled
    /// Builds will only fire in response to pull requests if:
    /// 1. The pull request author is a repository writer or above.
    /// 2. If the author does not have write permissions, a user with write
    /// permissions or above must comment `/gcbrun` in order to fire a build.
    case commentsEnabledForExternalContributorsOnly
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .commentsDisabled
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .commentsDisabled: return 0
      case .commentsEnabled: return 1
      case .commentsEnabledForExternalContributorsOnly: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .commentsDisabled: return "COMMENTS_DISABLED"
      case .commentsEnabled: return "COMMENTS_ENABLED"
      case .commentsEnabledForExternalContributorsOnly:
        return "COMMENTS_ENABLED_FOR_EXTERNAL_CONTRIBUTORS_ONLY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:CommentControl/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "COMMENTS_DISABLED": self = .commentsDisabled
      case "COMMENTS_ENABLED": self = .commentsEnabled
      case "COMMENTS_ENABLED_FOR_EXTERNAL_CONTRIBUTORS_ONLY":
        self = .commentsEnabledForExternalContributorsOnly
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:CommentControl/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .commentsDisabled
      case 1: self = .commentsEnabled
      case 2: self = .commentsEnabledForExternalContributorsOnly
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .commentsDisabled: return try container.encode(0)
      case .commentsEnabled: return try container.encode(1)
      case .commentsEnabledForExternalContributorsOnly: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Target refs to match.
  /// A target ref is the git reference where the pull request will be applied.
  public enum OneOf_GitRef: Codable, Equatable, Sendable {
    /// Regex of branches to match.
    ///
    /// The syntax of the regular expressions accepted is the syntax accepted by
    /// RE2 and described at https://github.com/google/re2/wiki/Syntax
    case branch(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.cloudbuild.v1.PullRequestFilter"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
