// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Push contains filter properties for matching GitHub git pushes.
public struct PushFilter: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// When true, only trigger a build if the revision regex does NOT match the
  /// git_ref regex.
  public var invertRegex: Swift.Bool = Swift.Bool()

  /// Modified refs to match.
  /// A modified refs are the refs modified by a git push operation.
  public var gitRef: OneOf_GitRef? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `PushFilter`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PushFilter().with { $0.branch = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let branch = CodingKeys(stringValue: "branch")
    static let tag = CodingKeys(stringValue: "tag")
    static let invertRegex = CodingKeys(stringValue: "invertRegex")

    static let _knownKeys: Set<Swift.String> = [
      "branch",
      "tag",
      "invertRegex",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .invertRegex) {
      self.invertRegex = value
    }

    var gitRef: OneOf_GitRef? = nil
    let gitRefCheckAndSet = {
      if gitRef != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'gitRef'"))
      }
      gitRef = $0
    }
    if let branch = try container.decodeIfPresent(Swift.String.self, forKey: .branch) {
      try gitRefCheckAndSet(.branch(branch))
    }
    if let tag = try container.decodeIfPresent(Swift.String.self, forKey: .tag) {
      try gitRefCheckAndSet(.tag(tag))
    }
    self.gitRef = gitRef
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.invertRegex, forKey: .invertRegex)

    if let choice = self.gitRef {
      switch choice {
      case .branch(let value):
        try container.encode(value, forKey: .branch)
      case .tag(let value):
        try container.encode(value, forKey: .tag)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Modified refs to match.
  /// A modified refs are the refs modified by a git push operation.
  public enum OneOf_GitRef: Codable, Equatable, Sendable {
    /// Regexes matching branches to build.
    ///
    /// The syntax of the regular expressions accepted is the syntax accepted by
    /// RE2 and described at https://github.com/google/re2/wiki/Syntax
    case branch(Swift.String)
    /// Regexes matching tags to build.
    ///
    /// The syntax of the regular expressions accepted is the syntax accepted by
    /// RE2 and described at https://github.com/google/re2/wiki/Syntax
    case tag(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.cloudbuild.v1.PushFilter"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
