// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleApi
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// ReceiveTriggerWebhookRequest [Experimental] is the request object accepted by
/// the ReceiveTriggerWebhook method.
public struct ReceiveTriggerWebhookRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The name of the `ReceiveTriggerWebhook` to retrieve.
  /// Format: `projects/{project}/locations/{location}/triggers/{trigger}`
  public var name: Swift.String = Swift.String()

  /// HTTP request body.
  public var body: GoogleApi.HttpBody? = nil

  /// Project in which the specified trigger lives
  public var projectId: Swift.String = Swift.String()

  /// Name of the trigger to run the payload against
  public var trigger: Swift.String = Swift.String()

  /// Secret token used for authorization if an OAuth token isn't provided.
  public var secret: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `ReceiveTriggerWebhookRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ReceiveTriggerWebhookRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let body = CodingKeys(stringValue: "body")
    static let projectId = CodingKeys(stringValue: "projectId")
    static let trigger = CodingKeys(stringValue: "trigger")
    static let secret = CodingKeys(stringValue: "secret")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "body",
      "projectId",
      "trigger",
      "secret",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.body = try container.decodeIfPresent(GoogleApi.HttpBody.self, forKey: .body)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .projectId) {
      self.projectId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .trigger) {
      self.trigger = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .secret) {
      self.secret = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.body, forKey: .body)
    try container.encode(self.projectId, forKey: .projectId)
    try container.encode(self.trigger, forKey: .trigger)
    try container.encode(self.secret, forKey: .secret)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.cloudbuild.v1.ReceiveTriggerWebhookRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
