// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The configuration of a trigger that creates a build whenever an event from
/// Repo API is received.
public struct RepositoryEventConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The resource name of the Repo API resource.
  public var repository: Swift.String = Swift.String()

  /// Output only. The type of the SCM vendor the repository points to.
  public var repositoryType: RepositoryEventConfig.RepositoryType =
    RepositoryEventConfig.RepositoryType()

  /// The types of filter to trigger a build.
  public var filter: OneOf_Filter? = nil

  /// Initialize a new instance of `RepositoryEventConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RepositoryEventConfig().with { $0.repository = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case repository = "repository"
    case repositoryType = "repositoryType"
    case pullRequest = "pullRequest"
    case push = "push"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.repository = try container.decode(Swift.String.self, forKey: .repository)
    self.repositoryType = try container.decode(
      RepositoryEventConfig.RepositoryType.self, forKey: .repositoryType)

    var filter: OneOf_Filter? = nil
    let filterCheckAndSet = {
      if filter != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'filter'"))
      }
      filter = $0
    }
    if let pullRequest = try container.decodeIfPresent(
      PullRequestFilter?.self, forKey: .pullRequest)
    {
      try filterCheckAndSet(.pullRequest(pullRequest))
    }
    if let push = try container.decodeIfPresent(PushFilter?.self, forKey: .push) {
      try filterCheckAndSet(.push(push))
    }
    self.filter = filter
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.repository, forKey: .repository)
    try container.encode(self.repositoryType, forKey: .repositoryType)

    if let choice = self.filter {
      switch choice {
      case .pullRequest(let value):
        try container.encode(value, forKey: .pullRequest)
      case .push(let value):
        try container.encode(value, forKey: .push)
      }
    }
  }

  /// All possible SCM repo types from Repo API.
  public enum RepositoryType: Codable, Equatable, Sendable {
    /// If unspecified, RepositoryType defaults to GITHUB.
    case unspecified
    /// The SCM repo is GITHUB.
    case github
    /// The SCM repo is GITHUB Enterprise.
    case githubEnterprise
    /// The SCM repo is GITLAB Enterprise.
    case gitlabEnterprise
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .github: return 1
      case .githubEnterprise: return 2
      case .gitlabEnterprise: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "REPOSITORY_TYPE_UNSPECIFIED"
      case .github: return "GITHUB"
      case .githubEnterprise: return "GITHUB_ENTERPRISE"
      case .gitlabEnterprise: return "GITLAB_ENTERPRISE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:RepositoryType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "REPOSITORY_TYPE_UNSPECIFIED": self = .unspecified
      case "GITHUB": self = .github
      case "GITHUB_ENTERPRISE": self = .githubEnterprise
      case "GITLAB_ENTERPRISE": self = .gitlabEnterprise
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:RepositoryType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .github
      case 2: self = .githubEnterprise
      case 3: self = .gitlabEnterprise
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .github: return try container.encode(1)
      case .githubEnterprise: return try container.encode(2)
      case .gitlabEnterprise: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The types of filter to trigger a build.
  public enum OneOf_Filter: Codable, Equatable, Sendable {
    /// Filter to match changes in pull requests.
    indirect case pullRequest(PullRequestFilter?)
    /// Filter to match changes in refs like branches, tags.
    indirect case push(PushFilter?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.cloudbuild.v1.RepositoryEventConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
