// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Location of the source in a Google Cloud Source Repository.
public struct RepoSource: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. ID of the project that owns the Cloud Source Repository. If
  /// omitted, the project ID requesting the build is assumed.
  public var projectId: Swift.String = Swift.String()

  /// Required. Name of the Cloud Source Repository.
  public var repoName: Swift.String = Swift.String()

  /// Optional. Directory, relative to the source root, in which to run the
  /// build.
  ///
  /// This must be a relative path. If a step's `dir` is specified and is an
  /// absolute path, this value is ignored for that step's execution.
  public var dir: Swift.String = Swift.String()

  /// Optional. Only trigger a build if the revision regex does NOT match the
  /// revision regex.
  public var invertRegex: Swift.Bool = Swift.Bool()

  /// Optional. Substitutions to use in a triggered build.
  /// Should only be used with RunBuildTrigger
  public var substitutions: [Swift.String: Swift.String] = [:]

  /// A revision within the Cloud Source Repository must be specified in
  /// one of these ways.
  public var revision: RevisionOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `RepoSource`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RepoSource().with { $0.projectId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let projectId = CodingKeys(stringValue: "projectId")
    static let repoName = CodingKeys(stringValue: "repoName")
    static let branchName = CodingKeys(stringValue: "branchName")
    static let tagName = CodingKeys(stringValue: "tagName")
    static let commitSha = CodingKeys(stringValue: "commitSha")
    static let dir = CodingKeys(stringValue: "dir")
    static let invertRegex = CodingKeys(stringValue: "invertRegex")
    static let substitutions = CodingKeys(stringValue: "substitutions")

    static let _knownKeys: Set<Swift.String> = [
      "projectId",
      "repoName",
      "branchName",
      "tagName",
      "commitSha",
      "dir",
      "invertRegex",
      "substitutions",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .projectId) {
      self.projectId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .repoName) {
      self.repoName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .dir) {
      self.dir = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .invertRegex) {
      self.invertRegex = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .substitutions)
    {
      self.substitutions = value
    }

    var revision: RevisionOneOf? = nil
    let revisionCheckAndSet = {
      if revision != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'revision'"))
      }
      revision = $0
    }
    if let branchName = try container.decodeIfPresent(Swift.String.self, forKey: .branchName) {
      try revisionCheckAndSet(.branchName(branchName))
    }
    if let tagName = try container.decodeIfPresent(Swift.String.self, forKey: .tagName) {
      try revisionCheckAndSet(.tagName(tagName))
    }
    if let commitSha = try container.decodeIfPresent(Swift.String.self, forKey: .commitSha) {
      try revisionCheckAndSet(.commitSha(commitSha))
    }
    self.revision = revision
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.projectId, forKey: .projectId)
    try container.encode(self.repoName, forKey: .repoName)
    try container.encode(self.dir, forKey: .dir)
    try container.encode(self.invertRegex, forKey: .invertRegex)
    try container.encode(self.substitutions, forKey: .substitutions)

    if let choice = self.revision {
      switch choice {
      case .branchName(let value):
        try container.encode(value, forKey: .branchName)
      case .tagName(let value):
        try container.encode(value, forKey: .tagName)
      case .commitSha(let value):
        try container.encode(value, forKey: .commitSha)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// A revision within the Cloud Source Repository must be specified in
  /// one of these ways.
  public enum RevisionOneOf: Codable, Equatable, Sendable {
    /// Regex matching branches to build.
    ///
    /// The syntax of the regular expressions accepted is the syntax accepted by
    /// RE2 and described at https://github.com/google/re2/wiki/Syntax
    case branchName(Swift.String)
    /// Regex matching tags to build.
    ///
    /// The syntax of the regular expressions accepted is the syntax accepted by
    /// RE2 and described at https://github.com/google/re2/wiki/Syntax
    case tagName(Swift.String)
    /// Explicit commit SHA to build.
    case commitSha(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.cloudbuild.v1.RepoSource"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
