// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Provenance of the source. Ways to find the original source, or verify that
/// some source was used for this build.
public struct SourceProvenance: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// A copy of the build's `source.storage_source`, if exists, with any
  /// generations resolved.
  public var resolvedStorageSource: StorageSource? = nil

  /// A copy of the build's `source.repo_source`, if exists, with any
  /// revisions resolved.
  public var resolvedRepoSource: RepoSource? = nil

  /// A copy of the build's `source.storage_source_manifest`, if exists, with any
  /// revisions resolved.
  /// This feature is in Preview.
  public var resolvedStorageSourceManifest: StorageSourceManifest? = nil

  /// Output only. A copy of the build's `source.connected_repository`, if
  /// exists, with any revisions resolved.
  public var resolvedConnectedRepository: ConnectedRepository? = nil

  /// Output only. A copy of the build's `source.git_source`, if exists, with any
  /// revisions resolved.
  public var resolvedGitSource: GitSource? = nil

  /// Output only. Hash(es) of the build source, which can be used to verify that
  /// the original source integrity was maintained in the build. Note that
  /// `FileHashes` will only be populated if `BuildOptions` has requested a
  /// `SourceProvenanceHash`.
  ///
  /// The keys to this map are file paths used as build source and the values
  /// contain the hash values for those files.
  ///
  /// If the build source came in a single package such as a gzipped tarfile
  /// (`.tar.gz`), the `FileHash` will be for the single path to that file.
  public var fileHashes: [Swift.String: FileHashes] = [:]

  /// Initialize a new instance of `SourceProvenance`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SourceProvenance().with { $0.resolvedStorageSource = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.cloudbuild.v1.SourceProvenance"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
