// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Location of the source manifest in Cloud Storage.
/// This feature is in Preview; see description
/// [here](https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/gcs-fetcher).
public struct StorageSourceManifest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Cloud Storage bucket containing the source manifest (see [Bucket
  /// Name
  /// Requirements](https://cloud.google.com/storage/docs/bucket-naming#requirements)).
  public var bucket: Swift.String = Swift.String()

  /// Required. Cloud Storage object containing the source manifest.
  ///
  /// This object must be a JSON file.
  public var object: Swift.String = Swift.String()

  /// Cloud Storage generation for the object. If the generation is
  /// omitted, the latest generation will be used.
  public var generation: Swift.Int64 = Swift.Int64()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `StorageSourceManifest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = StorageSourceManifest().with { $0.bucket = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let bucket = CodingKeys(stringValue: "bucket")
    static let object = CodingKeys(stringValue: "object")
    static let generation = CodingKeys(stringValue: "generation")

    static let _knownKeys: Set<Swift.String> = [
      "bucket",
      "object",
      "generation",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .bucket) {
      self.bucket = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .object) {
      self.object = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .generation) {
      self.generation = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.bucket, forKey: .bucket)
    try container.encode(self.object, forKey: .object)
    try container.encode(self.generation, forKey: .generation)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.cloudbuild.v1.StorageSourceManifest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
