// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request to update an existing `BuildTrigger`.
public struct UpdateBuildTriggerRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. ID of the project that owns the trigger.
  public var projectId: Swift.String = Swift.String()

  /// Required. ID of the `BuildTrigger` to update.
  public var triggerId: Swift.String = Swift.String()

  /// Required. `BuildTrigger` to update.
  public var trigger: BuildTrigger? = nil

  /// Update mask for the resource. If this is set,
  /// the server will only update the fields specified in the field mask.
  /// Otherwise, a full update of the mutable resource fields will be performed.
  public var updateMask: GoogleCloudWkt.FieldMask? = nil

  /// Initialize a new instance of `UpdateBuildTriggerRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateBuildTriggerRequest().with { $0.projectId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.cloudbuild.v1.UpdateBuildTriggerRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
