// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A Go module artifact uploaded to Artifact Registry using the GoModule
/// directive.
public struct UploadedGoModule: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// URI of the uploaded artifact.
  public var uri: Swift.String = Swift.String()

  /// Hash types and values of the Go Module Artifact.
  public var fileHashes: FileHashes? = nil

  /// Output only. Stores timing information for pushing the specified artifact.
  public var pushTiming: TimeSpan? = nil

  /// Output only. Path to the artifact in Artifact Registry.
  public var artifactRegistryPackage: Swift.String = Swift.String()

  /// Initialize a new instance of `UploadedGoModule`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UploadedGoModule().with { $0.uri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.cloudbuild.v1.UploadedGoModule"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
